/**
 * Unsplash photographs for /photos. Standard and Ultra tiles are stored in
 * Supabase Storage under static/gainmaps.com/photos/{slug}/. standard-*.jpg
 * is the SDR base via `gainmap extract-sdr`; gainmap-*.jpg is Ultra HDR.
 * Responsive widths: 400, 800, 1280, 1600, 2048, 2560.
 *
 * Rebuild: npx tsx tools/photos/build-photos.ts
 */

export const PHOTO_SRC_WIDTHS = [400, 800, 1280, 1600, 2048, 2560] as const;
export const PHOTO_STORAGE_BASE_URL = (
  process.env.NEXT_PUBLIC_PHOTO_STORAGE_BASE_URL
  ?? "https://icquwwyymqnvhcpufxje.supabase.co/storage/v1/object/public/static/gainmaps.com"
).replace(/\/+$/, "");

export const PHOTO_GALLERY_SIZES =
  "(min-width: 1280px) 384px, (min-width: 1024px) calc((100vw - 8rem) / 3), (min-width: 640px) 45vw, calc(100vw - 2rem)";

export const PHOTO_HERO_SIZES = "(min-width: 1024px) calc(100vw - 564px), calc(100vw - 2rem)";

export type Photo = {
  readonly id: string;
  readonly slug: string;
  /** images.unsplash.com filename, e.g. photo-1506905925346-21bda4d32df4 */
  readonly unsplashPhotoId: string;
  readonly photographer: string;
  readonly photographerUrl: string;
  readonly photoUrl: string;
  readonly width: number;
  readonly height: number;
  readonly alt: string;
};

export const PAGE_SIZE = 12;

export const PHOTOS: readonly Photo[] = [
  { id: "qsdkMlbfne4", slug: "a-seal-rests-on-a-shallow-sandbar-in-calm-water", unsplashPhotoId: "photo-1784978516675-8daa424836f5", photographer: "Jeremy Hynes", photographerUrl: "https://unsplash.com/@hynesight", photoUrl: "https://unsplash.com/photos/a-seal-rests-on-a-shallow-sandbar-in-calm-water-qsdkMlbfne4", width: 7660, height: 3830, alt: "A seal rests on a shallow sandbar in calm water" },
  { id: "l3Pvd4M3Css", slug: "low-sun-with-lens-flare-over-a-forested-valley-and-granite-c", unsplashPhotoId: "photo-1787170426598-858e57c774dd", photographer: "Priyank Pathak", photographerUrl: "https://unsplash.com/@ppriyank", photoUrl: "https://unsplash.com/photos/low-sun-over-yosemite-valley-cliffs-l3Pvd4M3Css", width: 9459, height: 5475, alt: "Low sun with lens flare over a forested valley and granite cliffs in Yosemite" },
  { id: "maKSDW4Ucoc", slug: "a-person-walks-along-a-desert-sand-dune-at-sunset", unsplashPhotoId: "photo-1781902834540-4604713b7e1b", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/a-person-walks-along-a-desert-sand-dune-at-sunset-maKSDW4Ucoc", width: 3525, height: 5287, alt: "A person walks along a desert sand dune at sunset" },
  { id: "ygRIDv3W6Ec", slug: "zebras-in-a-golden-sunlit-grassy-field", unsplashPhotoId: "photo-1781730655215-63a2a92623e4", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/zebras-in-a-golden-sunlit-grassy-field-ygRIDv3W6Ec", width: 5713, height: 3809, alt: "Zebras in a golden, sunlit grassy field" },
  { id: "qsQNjjHjFns", slug: "striking-layered-desert-mountain-under-a-beautiful-sunset-sk", unsplashPhotoId: "photo-1785142893888-58e3954672db", photographer: "Kilic-Emre Akdag", photographerUrl: "https://unsplash.com/@kilicemre7007", photoUrl: "https://unsplash.com/photos/striking-layered-desert-mountain-under-a-beautiful-sunset-sky-qsQNjjHjFns", width: 4024, height: 3018, alt: "Striking layered desert mountain under a beautiful sunset sky" },
  { id: "i_J0c5m6yvc", slug: "a-person-in-a-red-cloak-on-a-vast-sand-dune-at-golden-hour", unsplashPhotoId: "photo-1786300412449-875316124ba1", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/person-in-red-cloak-on-sand-dune-i_J0c5m6yvc", width: 4382, height: 6573, alt: "A person in a red cloak on a vast sand dune at golden hour" },
  { id: "j0M14wYc1_A", slug: "wooden-cabin-in-a-lush-green-meadow-before-a-mountain", unsplashPhotoId: "photo-1784019226271-f89c21f7791a", photographer: "Yousef Salhamoud", photographerUrl: "https://unsplash.com/@salhamoud", photoUrl: "https://unsplash.com/photos/wooden-cabin-in-a-lush-green-meadow-before-a-mountain-j0M14wYc1_A", width: 4470, height: 6705, alt: "Wooden cabin in a lush green meadow before a mountain" },
  { id: "I_n_b44cqhk", slug: "green-mountains-under-blue-sky-during-daytime", unsplashPhotoId: "photo-1612441804231-77a36b284856", photographer: "Simon Lohmann", photographerUrl: "https://unsplash.com/@slohmann", photoUrl: "https://unsplash.com/photos/green-mountains-under-blue-sky-during-daytime-I_n_b44cqhk", width: 6720, height: 4480, alt: "green mountains under blue sky during daytime" },
  { id: "s-y2HJElONo", slug: "green-grass-field-and-mountains-under-white-clouds-and-blue-sky", unsplashPhotoId: "photo-1610552050890-fe99536c2615", photographer: "lucas wesney", photographerUrl: "https://unsplash.com/@wesnext", photoUrl: "https://unsplash.com/photos/green-grass-field-and-mountains-under-white-clouds-and-blue-sky-during-daytime-s-y2HJElONo", width: 7891, height: 5051, alt: "green grass field and mountains under white clouds and blue sky during daytime" },
  { id: "-g7axSVst6Y", slug: "landscape-photography-of-mountain-ranges-under-purple-and-pink", unsplashPhotoId: "photo-1466854076813-4aa9ac0fc347", photographer: "Štefan Štefančík", photographerUrl: "https://unsplash.com/@cikstefan", photoUrl: "https://unsplash.com/photos/landscape-photography-of-mountain-ranges-under-purple-and-pink-skies--g7axSVst6Y", width: 2400, height: 1350, alt: "landscape photography of mountain ranges under purple and pink skies" },
  { id: "rQqWOHZ96OM", slug: "snow-capped-mountains-at-daytime", unsplashPhotoId: "photo-1515268064940-5150b7c29f35", photographer: "John Rodenn Castillo", photographerUrl: "https://unsplash.com/@nightcrawler1986", photoUrl: "https://unsplash.com/photos/snow-capped-mountains-at-daytime-rQqWOHZ96OM", width: 3888, height: 2592, alt: "snow capped mountains at daytime" },
  { id: "1YQDhLtB9yU", slug: "green-trees-and-snow-covered-mountains-during-daytime", unsplashPhotoId: "photo-1604428803896-c1e5151d4128", photographer: "Hendrik Kespohl", photographerUrl: "https://unsplash.com/@hendrikkay", photoUrl: "https://unsplash.com/photos/green-trees-and-snow-covered-mountains-during-daytime-1YQDhLtB9yU", width: 5184, height: 3456, alt: "green trees and snow covered mountains during daytime" },
  { id: "pl1mhwMctJc", slug: "red-tent-on-grass-field-beside-ice-capped-mountain-nature-photo", unsplashPhotoId: "photo-1464547323744-4edd0cd0c746", photographer: "Dino Reichmuth", photographerUrl: "https://unsplash.com/@dinoreichmuth", photoUrl: "https://unsplash.com/photos/red-tent-on-grass-field-beside-ice-capped-mountain-nature-photography-pl1mhwMctJc", width: 5616, height: 3744, alt: "red tent on grass field beside ice capped mountain nature photography" },
  { id: "NuBvAE6VfSM", slug: "black-and-white-mountains-under-white-sky-during-daytime", unsplashPhotoId: "photo-1609342122563-a43ac8917a3a", photographer: "Tobias Rademacher", photographerUrl: "https://unsplash.com/@tobbes_rd", photoUrl: "https://unsplash.com/photos/black-and-white-mountains-under-white-sky-during-daytime-NuBvAE6VfSM", width: 6316, height: 4211, alt: "black and white mountains under white sky during daytime" },
  { id: "tKyt-GZowHQ", slug: "field-of-brown-grasses-within-mountain-range", unsplashPhotoId: "photo-1446488614340-2d1a68d662f9", photographer: "Keghan Crossland", photographerUrl: "https://unsplash.com/@keghancphoto", photoUrl: "https://unsplash.com/photos/field-of-brown-grasses-within-mountain-range-tKyt-GZowHQ", width: 4240, height: 2832, alt: "field of brown grasses within mountain range" },
  { id: "rlV0CJDxtX0", slug: "an-aerial-view-of-a-snow-covered-mountain", unsplashPhotoId: "photo-1647291624328-0150933d5d05", photographer: "Christian Wiebel", photographerUrl: "https://unsplash.com/@chriswis", photoUrl: "https://unsplash.com/photos/an-aerial-view-of-a-snow-covered-mountain-rlV0CJDxtX0", width: 4000, height: 2667, alt: "an aerial view of a snow covered mountain" },
  { id: "mkdI8JN6sDU", slug: "grey-and-white-mountain", unsplashPhotoId: "photo-1469212044023-0e55b4b9745a", photographer: "Matheus Bandoch", photographerUrl: "https://unsplash.com/@mbandoch", photoUrl: "https://unsplash.com/photos/grey-and-white-mountain-mkdI8JN6sDU", width: 4928, height: 3264, alt: "grey and white mountain" },
  { id: "EhnHNsHl3sU", slug: "a-lake-in-the-middle-of-a-mountain-range", unsplashPhotoId: "photo-1699786023101-2181d624d234", photographer: "Yevhenii Dubrovskyi", photographerUrl: "https://unsplash.com/@dbr0vskyi", photoUrl: "https://unsplash.com/photos/a-lake-in-the-middle-of-a-mountain-range-EhnHNsHl3sU", width: 7008, height: 4672, alt: "a lake in the middle of a mountain range" },
  { id: "T0PaR22Kv8k", slug: "a-view-of-a-body-of-water-from-a-hill", unsplashPhotoId: "photo-1707007785777-9324ce8cf42d", photographer: "Phill Brown", photographerUrl: "https://unsplash.com/@phillbrown", photoUrl: "https://unsplash.com/photos/a-view-of-a-body-of-water-from-a-hill-T0PaR22Kv8k", width: 5970, height: 3980, alt: "a view of a body of water from a hill" },
  { id: "S7YTvzJnf0w", slug: "a-view-of-a-beach-with-waves-coming-in-to-shore", unsplashPhotoId: "photo-1707007730851-c53cc2879f00", photographer: "Phill Brown", photographerUrl: "https://unsplash.com/@phillbrown", photoUrl: "https://unsplash.com/photos/a-view-of-a-beach-with-waves-coming-in-to-shore-S7YTvzJnf0w", width: 5224, height: 3483, alt: "a view of a beach with waves coming in to shore" },
  { id: "TWoL-QCZubY", slug: "body-of-water-near-trees-and-mountain-cliff-during-daytime", unsplashPhotoId: "photo-1510414842594-a61c69b5ae57", photographer: "Derek Thomson", photographerUrl: "https://unsplash.com/@derekthomson", photoUrl: "https://unsplash.com/photos/body-of-water-near-trees-and-mountain-cliff-during-daytime-TWoL-QCZubY", width: 5472, height: 3648, alt: "body of water near trees and mountain cliff during daytime" },
  { id: "_e-8w6ZM9ZI", slug: "photo-of-sea-wave-crashing-shore", unsplashPhotoId: "photo-1474180348636-b816e168b85e", photographer: "Colin Maynard", photographerUrl: "https://unsplash.com/@fromnineteen80", photoUrl: "https://unsplash.com/photos/photo-of-sea-wave-crashing-shore-_e-8w6ZM9ZI", width: 2500, height: 1667, alt: "photo of sea wave crashing shore" },
  { id: "cuTk59eNHUE", slug: "aerial-photo-body-of-water", unsplashPhotoId: "photo-1444260239795-df1f0772a252", photographer: "Mathew Waters", photographerUrl: "https://unsplash.com/@mathew_waters", photoUrl: "https://unsplash.com/photos/aerial-photo-body-of-water-cuTk59eNHUE", width: 3456, height: 2304, alt: "aerial photo body of water" },
  { id: "QFVsotOQ4Mg", slug: "black-and-white-ocean-waves-crashing-against-a-rocky-shore", unsplashPhotoId: "photo-1785335872743-1b391da814cb", photographer: "gianna branco", photographerUrl: "https://unsplash.com/@gianna_branco", photoUrl: "https://unsplash.com/photos/black-and-white-ocean-waves-crashing-against-a-rocky-shore-QFVsotOQ4Mg", width: 3637, height: 2374, alt: "Black and white ocean waves crashing against a rocky shore" },
  { id: "0eukOYdCfHY", slug: "large-waves-crash-against-dark-rocks-under-a-grey-sky", unsplashPhotoId: "photo-1778846181379-bc907c811d28", photographer: "Wolfgang Hasselmann", photographerUrl: "https://unsplash.com/@wolfgang_hasselmann", photoUrl: "https://unsplash.com/photos/large-waves-crash-against-dark-rocks-under-a-grey-sky-0eukOYdCfHY", width: 7008, height: 4672, alt: "Large waves crash against dark rocks under a grey sky" },
  { id: "zGto-tO0-_c", slug: "turquoise-waves-crashing-on-a-sandy-shore", unsplashPhotoId: "photo-1763866522069-abe2d1129b3a", photographer: "Fumiaki Hayashi", photographerUrl: "https://unsplash.com/@fumirin", photoUrl: "https://unsplash.com/photos/turquoise-waves-crashing-on-a-sandy-shore-zGto-tO0-_c", width: 6240, height: 4160, alt: "Turquoise waves crashing on a sandy shore" },
  { id: "d3pTF3r_hwY", slug: "mountains-covered-with-snow", unsplashPhotoId: "photo-1483921020237-2ff51e8e4b22", photographer: "Erol Ahmed", photographerUrl: "https://unsplash.com/@erol", photoUrl: "https://unsplash.com/photos/mountains-covered-with-snow-d3pTF3r_hwY", width: 5472, height: 3648, alt: "mountains covered with snow" },
  { id: "QRdX9dO8poY", slug: "snow-covered-mountains-during-daytime", unsplashPhotoId: "photo-1542379521-3410aec637d1", photographer: "Darya Sev", photographerUrl: "https://unsplash.com/@darya_sev", photoUrl: "https://unsplash.com/photos/snow-covered-mountains-during-daytime-QRdX9dO8poY", width: 3290, height: 2193, alt: "snow covered mountains during daytime" },
  { id: "eSkLHB83Oso", slug: "snow-on-rock-mountain", unsplashPhotoId: "photo-1559586526-3a7665d40fdc", photographer: "Chad Tetzlaff", photographerUrl: "https://unsplash.com/@chadtetz", photoUrl: "https://unsplash.com/photos/snow-on-rock-mountain-eSkLHB83Oso", width: 4028, height: 2266, alt: "snow on rock mountain" },
  { id: "WQx4_R4jjJA", slug: "aerial-photo-of-snow-covered-mountains", unsplashPhotoId: "photo-1500937078812-a4aea2239059", photographer: "Nicolas Prieto", photographerUrl: "https://unsplash.com/@nicolasp", photoUrl: "https://unsplash.com/photos/aerial-photo-of-snow-covered-mountains-WQx4_R4jjJA", width: 3999, height: 2406, alt: "aerial photo of snow covered mountains" },
  { id: "N_MXyBUV5hU", slug: "landscape-photo-of-snowy-mountain", unsplashPhotoId: "photo-1519931760384-a96fedd8dfa9", photographer: "Karl Köhler", photographerUrl: "https://unsplash.com/@karlkoehler", photoUrl: "https://unsplash.com/photos/landscape-photo-of-snowy-mountain-N_MXyBUV5hU", width: 3303, height: 2206, alt: "landscape photo of snowy mountain" },
  { id: "iZTI6LVUVZ8", slug: "snow-covered-mountain-during-daytime", unsplashPhotoId: "photo-1626605962297-b85b963d373b", photographer: "Yaroslav Konyk", photographerUrl: "https://unsplash.com/@konyk_y", photoUrl: "https://unsplash.com/photos/snow-covered-mountain-during-daytime-iZTI6LVUVZ8", width: 4048, height: 3032, alt: "snow covered mountain during daytime" },
  { id: "0wr7gVk-ODY", slug: "a-train-traveling-through-a-snow-covered-mountain", unsplashPhotoId: "photo-1673901736468-5da43467b0ef", photographer: "Patrick Federi", photographerUrl: "https://unsplash.com/@federi", photoUrl: "https://unsplash.com/photos/a-train-traveling-through-a-snow-covered-mountain-0wr7gVk-ODY", width: 5464, height: 3640, alt: "a train traveling through a snow covered mountain" },
  { id: "0coUjTEqPGg", slug: "a-red-train-traveling-through-a-snow-covered-mountain", unsplashPhotoId: "photo-1673901736420-0bf90fcf1b27", photographer: "Patrick Federi", photographerUrl: "https://unsplash.com/@federi", photoUrl: "https://unsplash.com/photos/a-red-train-traveling-through-a-snow-covered-mountain-0coUjTEqPGg", width: 5464, height: 3640, alt: "a red train traveling through a snow covered mountain" },
  { id: "NmHmafm5QV8", slug: "a-train-traveling-through-a-snow-covered-forest", unsplashPhotoId: "photo-1673901736622-c3f06b08511f", photographer: "Patrick Federi", photographerUrl: "https://unsplash.com/@federi", photoUrl: "https://unsplash.com/photos/a-train-traveling-through-a-snow-covered-forest-NmHmafm5QV8", width: 9833, height: 6526, alt: "a train traveling through a snow covered forest" },
  { id: "nWMAakp1dKU", slug: "a-road-in-the-mountains", unsplashPhotoId: "photo-1662514146802-20d0650cde57", photographer: "Alain Bonnardeaux", photographerUrl: "https://unsplash.com/@bonnarda", photoUrl: "https://unsplash.com/photos/a-road-in-the-mountains-nWMAakp1dKU", width: 8256, height: 5504, alt: "a road in the mountains" },
  { id: "utFpVqZhunM", slug: "a-mountain-covered-in-snow", unsplashPhotoId: "photo-1667783749012-ab082ca87a01", photographer: "Chris Linnett", photographerUrl: "https://unsplash.com/@chrislinnett", photoUrl: "https://unsplash.com/photos/a-mountain-covered-in-snow-utFpVqZhunM", width: 4000, height: 3000, alt: "a mountain covered in snow" },
  { id: "SJdZWRLzWlY", slug: "body-of-water-near-black-mountains", unsplashPhotoId: "photo-1506792389040-ef95e711fb4b", photographer: "Matt Artz", photographerUrl: "https://unsplash.com/@mattartz", photoUrl: "https://unsplash.com/photos/body-of-water-near-black-mountains-SJdZWRLzWlY", width: 2964, height: 1956, alt: "body of water near black mountains" },
  { id: "7KTlL8vvrMk", slug: "a-large-snowy-landscape", unsplashPhotoId: "photo-1648538114895-e6f6ae2c54c3", photographer: "Colin + Meg", photographerUrl: "https://unsplash.com/@colinandmeg", photoUrl: "https://unsplash.com/photos/a-large-snowy-landscape-7KTlL8vvrMk", width: 4000, height: 2250, alt: "a large snowy landscape" },
  { id: "i0XNwkEnAWo", slug: "white-and-teal-glacier", unsplashPhotoId: "photo-1460954824840-97d4e5ae54bb", photographer: "Kyson Dana", photographerUrl: "https://unsplash.com/@kysondana", photoUrl: "https://unsplash.com/photos/white-and-teal-glacier-i0XNwkEnAWo", width: 3000, height: 1505, alt: "white and teal Glacier" },
  { id: "g8GdGmX0H_I", slug: "a-large-body-of-water-surrounded-by-mountains", unsplashPhotoId: "photo-1727229900061-32bb689f0fc6", photographer: "Karsten Winegeart", photographerUrl: "https://unsplash.com/@_karsten", photoUrl: "https://unsplash.com/photos/a-large-body-of-water-surrounded-by-mountains-g8GdGmX0H_I", width: 8064, height: 6048, alt: "A large body of water surrounded by mountains" },
  { id: "aJjIL9A-pAo", slug: "a-mountain-glacier-with-snow-and-ice", unsplashPhotoId: "photo-1745435659331-059202e27f7b", photographer: "Alek Newton", photographerUrl: "https://unsplash.com/@aleknewton", photoUrl: "https://unsplash.com/photos/a-mountain-glacier-with-snow-and-ice-aJjIL9A-pAo", width: 7952, height: 5304, alt: "A mountain glacier with snow and ice" },
  { id: "K7vG20_rdXw", slug: "a-group-of-people-standing-on-top-of-a-snow-covered-mountain", unsplashPhotoId: "photo-1682362868672-10a02f6b9b5e", photographer: "Henrique Ferreira", photographerUrl: "https://unsplash.com/@rickpsd", photoUrl: "https://unsplash.com/photos/a-group-of-people-standing-on-top-of-a-snow-covered-mountain-K7vG20_rdXw", width: 6960, height: 4640, alt: "a group of people standing on top of a snow covered mountain" },
  { id: "6kBBOAZpdd4", slug: "a-paraglider-is-flying-over-a-mountain-range", unsplashPhotoId: "photo-1718991308633-18590608aa15", photographer: "Cate Brodersen", photographerUrl: "https://unsplash.com/@cate_brodersen", photoUrl: "https://unsplash.com/photos/a-paraglider-is-flying-over-a-mountain-range-6kBBOAZpdd4", width: 9940, height: 6630, alt: "A paraglider is flying over a mountain range" },
  { id: "RtD0apVaAOo", slug: "snow-covered-mountain-range-under-a-bright-sky-with-buildings", unsplashPhotoId: "photo-1781458366563-f8ac7cc4b29a", photographer: "Barney Goodman", photographerUrl: "https://unsplash.com/@bgoodpic", photoUrl: "https://unsplash.com/photos/snow-covered-mountain-range-under-a-bright-sky-with-buildings-RtD0apVaAOo", width: 3130, height: 2075, alt: "Snow-covered mountain range under a bright sky with buildings" },
  { id: "QAxIz-7uWu4", slug: "glacier-mountains-during-day", unsplashPhotoId: "photo-1546180055-761f3f495b3c", photographer: "Valentin Kremer", photographerUrl: "https://unsplash.com/@vbk_media", photoUrl: "https://unsplash.com/photos/glacier-mountains-during-day-QAxIz-7uWu4", width: 6000, height: 3376, alt: "glacier mountains during day" },
  { id: "nrGLHomHs50", slug: "a-view-of-a-mountain-range-with-snow-on-it", unsplashPhotoId: "photo-1635884957479-32daac4aa009", photographer: "Carole Hachet", photographerUrl: "https://unsplash.com/@caroleha", photoUrl: "https://unsplash.com/photos/a-view-of-a-mountain-range-with-snow-on-it-nrGLHomHs50", width: 4096, height: 3072, alt: "a view of a mountain range with snow on it" },
  { id: "Y2zMzweH3gQ", slug: "gray-mountain", unsplashPhotoId: "photo-1576829021693-a6e2689fb7ca", photographer: "Marek Okon", photographerUrl: "https://unsplash.com/@marekokon", photoUrl: "https://unsplash.com/photos/gray-mountain-Y2zMzweH3gQ", width: 5703, height: 3802, alt: "gray mountain" },
  { id: "6tfO1M8_gas", slug: "mountain-with-trees-covered-with-fogs-at-daytime", unsplashPhotoId: "photo-1512923927402-a9867a68180e", photographer: "Chris Lawton", photographerUrl: "https://unsplash.com/@chrislawton", photoUrl: "https://unsplash.com/photos/mountain-with-trees-covered-with-fogs-at-daytime-6tfO1M8_gas", width: 6000, height: 4001, alt: "mountain with trees covered with fogs at daytime" },
  { id: "vA80ZTVyooc", slug: "trees-with-sun-rays", unsplashPhotoId: "photo-1542923910-f391dea9f674", photographer: "Dave Hoefler", photographerUrl: "https://unsplash.com/@iamthedave", photoUrl: "https://unsplash.com/photos/trees-with-sun-rays-vA80ZTVyooc", width: 5760, height: 3600, alt: "trees with sun rays" },
  { id: "6mU7uCAO64I", slug: "sun-rays-in-forest", unsplashPhotoId: "photo-1530563937443-1f02f662fa5c", photographer: "Dale Nibbe", photographerUrl: "https://unsplash.com/@dalenmt", photoUrl: "https://unsplash.com/photos/sun-rays-in-forest-6mU7uCAO64I", width: 4032, height: 3024, alt: "sun rays in forest" },
  { id: "zIBetXW-WRk", slug: "the-sun-is-shining-through-the-clouds-over-the-trees", unsplashPhotoId: "photo-1732271929784-398a2a714b1e", photographer: "Gabriel Herter", photographerUrl: "https://unsplash.com/@gibbivision", photoUrl: "https://unsplash.com/photos/the-sun-is-shining-through-the-clouds-over-the-trees-zIBetXW-WRk", width: 6000, height: 4000, alt: "The sun is shining through the clouds over the trees" },
  { id: "4EvreRzmq44", slug: "foggy-trees-covered-in-a-misty-haze", unsplashPhotoId: "photo-1745750747228-d7ae37cba3a5", photographer: "Dario Jud", photographerUrl: "https://unsplash.com/@dariojud_", photoUrl: "https://unsplash.com/photos/foggy-trees-covered-in-a-misty-haze-4EvreRzmq44", width: 6048, height: 4024, alt: "Foggy trees covered in a misty haze" },
  { id: "mU-wz7JlJMc", slug: "a-white-sand-dune-under-a-blue-sky", unsplashPhotoId: "photo-1642617916560-77159bba9f2f", photographer: "David Whipple", photographerUrl: "https://unsplash.com/@iamdavidwhipple", photoUrl: "https://unsplash.com/photos/a-white-sand-dune-under-a-blue-sky-mU-wz7JlJMc", width: 5600, height: 4000, alt: "a white sand dune under a blue sky" },
  { id: "1W3I3k2hP1o", slug: "a-person-standing-on-top-of-a-sandy-hill", unsplashPhotoId: "photo-1672190158315-bf9196b798a0", photographer: "Caleb Jack", photographerUrl: "https://unsplash.com/@hitthetrailjack", photoUrl: "https://unsplash.com/photos/a-person-standing-on-top-of-a-sandy-hill-1W3I3k2hP1o", width: 6960, height: 4640, alt: "a person standing on top of a sandy hill" },
  { id: "DUhaqW7Z7dY", slug: "gray-desert", unsplashPhotoId: "photo-1494290684976-e84de6898624", photographer: "Doug Gates", photographerUrl: "https://unsplash.com/@mcgrue", photoUrl: "https://unsplash.com/photos/gray-desert-DUhaqW7Z7dY", width: 4640, height: 3092, alt: "gray desert" },
  { id: "imxNP5xaAVk", slug: "sand-dunes-stretch-into-the-distance-under-a-pale-sky", unsplashPhotoId: "photo-1750927302363-411f8f2abd13", photographer: "Coekieshots", photographerUrl: "https://unsplash.com/@coekieshots", photoUrl: "https://unsplash.com/photos/sand-dunes-stretch-into-the-distance-under-a-pale-sky-imxNP5xaAVk", width: 6000, height: 4000, alt: "Sand dunes stretch into the distance under a pale sky" },
  { id: "gMZTEr0bDj0", slug: "a-view-of-a-mountain-range-in-the-distance", unsplashPhotoId: "photo-1676763133003-2f8dbb84bf98", photographer: "Carrie Borden", photographerUrl: "https://unsplash.com/@carrie_borden", photoUrl: "https://unsplash.com/photos/a-view-of-a-mountain-range-in-the-distance-gMZTEr0bDj0", width: 6026, height: 4009, alt: "a view of a mountain range in the distance" },
  { id: "WEWQ5ym-kes", slug: "white-sand-under-blue-sky-during-daytime", unsplashPhotoId: "photo-1631210793108-872b697e8d04", photographer: "Renato Trentin", photographerUrl: "https://unsplash.com/@renatotrentin", photoUrl: "https://unsplash.com/photos/white-sand-under-blue-sky-during-daytime-WEWQ5ym-kes", width: 3264, height: 2448, alt: "white sand under blue sky during daytime" },
  { id: "PXdBkNF8rlk", slug: "icebergs-floating-on-body-of-water-during-daytime", unsplashPhotoId: "photo-1445966838217-f418f2601b54", photographer: "Anders Jildén", photographerUrl: "https://unsplash.com/@andersjilden", photoUrl: "https://unsplash.com/photos/icebergs-floating-on-body-of-water-during-daytime-PXdBkNF8rlk", width: 3000, height: 2000, alt: "icebergs floating on body of water during daytime" },
  { id: "kWsT6p_S3cY", slug: "two-icebergs-under-cloudy-sky-at-daytime", unsplashPhotoId: "photo-1523156774078-3c6207a9e292", photographer: "Danting Zhu", photographerUrl: "https://unsplash.com/@himalaya1788", photoUrl: "https://unsplash.com/photos/two-icebergs-under-cloudy-sky-at-daytime-kWsT6p_S3cY", width: 5616, height: 3744, alt: "two icebergs under cloudy sky at daytime" },
  { id: "eXHeq48Z-Q4", slug: "body-of-water-during-daytime", unsplashPhotoId: "photo-1476673160081-cf065607f449", photographer: "frank mckenna", photographerUrl: "https://unsplash.com/@frankiefoto", photoUrl: "https://unsplash.com/photos/body-of-water-during-daytime-eXHeq48Z-Q4", width: 4928, height: 3280, alt: "body of water during daytime" },
  { id: "vIGmrIuNr1k", slug: "body-of-water", unsplashPhotoId: "photo-1564224478612-9dedb7387a66", photographer: "Doug Bagg", photographerUrl: "https://unsplash.com/@dougbagg_", photoUrl: "https://unsplash.com/photos/body-of-water-vIGmrIuNr1k", width: 5917, height: 3945, alt: "body of water" },
  { id: "zFk1FdVSlOs", slug: "sea-waves-crashing-on-shore-during-sunset", unsplashPhotoId: "photo-1601725781442-22a1c2671db9", photographer: "Jenna Lee", photographerUrl: "https://unsplash.com/@jennalee89", photoUrl: "https://unsplash.com/photos/sea-waves-crashing-on-shore-during-sunset-zFk1FdVSlOs", width: 4032, height: 3024, alt: "sea waves crashing on shore during sunset" },
  { id: "xfJjQ-0QwiA", slug: "a-sandy-beach-with-waves-coming-in-to-shore", unsplashPhotoId: "photo-1621350032995-bb459e23287c", photographer: "Amy Clark", photographerUrl: "https://unsplash.com/@littleloud_co", photoUrl: "https://unsplash.com/photos/a-sandy-beach-with-waves-coming-in-to-shore-xfJjQ-0QwiA", width: 5140, height: 3427, alt: "A sandy beach with waves coming in to shore" },
  { id: "lLTwa21urpY", slug: "brown-and-white-mountain-under-white-clouds-during-daytime", unsplashPhotoId: "photo-1589887305888-6254d60b5308", photographer: "Mark König", photographerUrl: "https://unsplash.com/@markkoenig", photoUrl: "https://unsplash.com/photos/brown-and-white-mountain-under-white-clouds-during-daytime-lLTwa21urpY", width: 2880, height: 1920, alt: "brown and white mountain under white clouds during daytime" },
  { id: "M8spMIQcg24", slug: "mountain-range-with-snow-and-cloudy-sky", unsplashPhotoId: "photo-1472158450446-5d1e9e1f34cb", photographer: "Wilfried Santer", photographerUrl: "https://unsplash.com/@wsanter", photoUrl: "https://unsplash.com/photos/mountain-range-with-snow-and-cloudy-sky-M8spMIQcg24", width: 4273, height: 2404, alt: "mountain range with snow and cloudy sky" },
  { id: "BB0eIqCHibk", slug: "a-snowboarder-is-standing-on-the-top-of-a-mountain", unsplashPhotoId: "photo-1645452904386-f214605a999a", photographer: "laura adai", photographerUrl: "https://unsplash.com/@lauraadaiphoto", photoUrl: "https://unsplash.com/photos/a-snowboarder-is-standing-on-the-top-of-a-mountain-BB0eIqCHibk", width: 6193, height: 4134, alt: "a snowboarder is standing on the top of a mountain" },
  { id: "MIntQrFl8zY", slug: "turquoise-waves-crashing-on-a-dark-ocean", unsplashPhotoId: "photo-1773831061662-ac449cd22ecd", photographer: "Rafael Rodrigues", photographerUrl: "https://unsplash.com/@rrodriguesim", photoUrl: "https://unsplash.com/photos/turquoise-waves-crashing-on-a-dark-ocean-MIntQrFl8zY", width: 6240, height: 4160, alt: "Turquoise waves crashing on a dark ocean" },
  { id: "yIWXizbj7dM", slug: "green-trees-covered-by-fog", unsplashPhotoId: "photo-1628841380003-90e0e39b3ba1", photographer: "Julian Steenbergen", photographerUrl: "https://unsplash.com/@mamanofficial", photoUrl: "https://unsplash.com/photos/green-trees-covered-by-fog-yIWXizbj7dM", width: 5193, height: 3462, alt: "green trees covered by fog" },
  { id: "LMIu8ZD8PnQ", slug: "green-trees-covered-by-fog-LMIu8ZD8PnQ", unsplashPhotoId: "photo-1631264508765-b49496f3f45d", photographer: "Markos Mant", photographerUrl: "https://unsplash.com/@markosmant", photoUrl: "https://unsplash.com/photos/green-trees-covered-by-fog-LMIu8ZD8PnQ", width: 5464, height: 3636, alt: "green trees covered by fog" },
  { id: "TX7BMVwCDME", slug: "a-foggy-mountain-with-trees-in-the-foreground", unsplashPhotoId: "photo-1693325012025-44a677c80258", photographer: "kabita Darlami", photographerUrl: "https://unsplash.com/@itskabita", photoUrl: "https://unsplash.com/photos/a-foggy-mountain-with-trees-in-the-foreground-TX7BMVwCDME", width: 6048, height: 4024, alt: "a foggy mountain with trees in the foreground" },
  { id: "ANICl9V7BUA", slug: "brown-sand-in-closeup-photography", unsplashPhotoId: "photo-1543604502-9baac28067ad", photographer: "Wolfgang Hasselmann", photographerUrl: "https://unsplash.com/@wolfgang_hasselmann", photoUrl: "https://unsplash.com/photos/brown-sand-in-closeup-photography-ANICl9V7BUA", width: 6000, height: 4000, alt: "brown sand in closeup photography" },
  { id: "QmEos0q08TM", slug: "brown-desert-field", unsplashPhotoId: "photo-1520440718111-45fe694b330a", photographer: "Juliana Malta", photographerUrl: "https://unsplash.com/@julianamalta", photoUrl: "https://unsplash.com/photos/brown-desert-field-QmEos0q08TM", width: 3456, height: 2304, alt: "brown desert field" },
  { id: "JjWpEsLwe-0", slug: "brown-dessert-during-daytime", unsplashPhotoId: "photo-1564612123322-ec11b6e1930a", photographer: "Willian Justen de Vasconcellos", photographerUrl: "https://unsplash.com/@willianjusten", photoUrl: "https://unsplash.com/photos/brown-dessert-during-daytime-JjWpEsLwe-0", width: 6000, height: 3414, alt: "brown dessert during daytime" },
  { id: "KY511rTEHEY", slug: "brown-sand-under-blue-sky-during-daytime", unsplashPhotoId: "photo-1609179643787-da5bbef95ee2", photographer: "Eugene Ga", photographerUrl: "https://unsplash.com/@eugene_ga", photoUrl: "https://unsplash.com/photos/brown-sand-under-blue-sky-during-daytime-KY511rTEHEY", width: 4032, height: 3016, alt: "brown sand under blue sky during daytime" },
  { id: "XnRfkgcv0jQ", slug: "brown-desert", unsplashPhotoId: "photo-1557069469-a7b654fa455d", photographer: "Laurent Gence", photographerUrl: "https://unsplash.com/@lgence", photoUrl: "https://unsplash.com/photos/brown-desert-XnRfkgcv0jQ", width: 4896, height: 3264, alt: "brown desert" },
  { id: "M3u-DO9RalU", slug: "mountains-and-trees-are-reflected-in-a-calm-lake", unsplashPhotoId: "photo-1753372623416-bc8bf85eab06", photographer: "Bridget Smith", photographerUrl: "https://unsplash.com/@hikingdyke", photoUrl: "https://unsplash.com/photos/mountains-and-trees-are-reflected-in-a-calm-lake-M3u-DO9RalU", width: 6000, height: 4000, alt: "Mountains and trees are reflected in a calm lake" },
  { id: "_jf7U7Xy6Ng", slug: "a-calm-lake-reflecting-snow-capped-mountains-under-a-soft-sky-w", unsplashPhotoId: "photo-1786992689379-74c2e104ae39", photographer: "Azimbek Assarov", photographerUrl: "https://unsplash.com/@azimbek", photoUrl: "https://unsplash.com/photos/lake-reflecting-snow-capped-mountains-_jf7U7Xy6Ng", width: 5938, height: 3959, alt: "A calm lake reflecting snow-capped mountains under a soft sky with wildflowers in foreground" },
  { id: "UvOgLmtR5cU", slug: "a-small-cabin-in-the-middle-of-a-lake", unsplashPhotoId: "photo-1708884908558-8c47153a7989", photographer: "Anthony Da Cruz", photographerUrl: "https://unsplash.com/@akhu", photoUrl: "https://unsplash.com/photos/a-small-cabin-in-the-middle-of-a-lake-UvOgLmtR5cU", width: 5820, height: 3880, alt: "a small cabin in the middle of a lake" },
  { id: "o75824r-9HE", slug: "snow-capped-mountains-reflected-in-the-calm-water-of-a-lake-at", unsplashPhotoId: "photo-1786288675590-8cc7162795d4", photographer: "Martin Leitgeb", photographerUrl: "https://unsplash.com/@martin_leitgeb_photos", photoUrl: "https://unsplash.com/photos/snow-capped-mountains-reflected-in-lake-o75824r-9HE", width: 6192, height: 3483, alt: "Snow-capped mountains reflected in the calm water of a lake at low light" },
  { id: "WTmJ13mh8XQ", slug: "a-town-with-glowing-streetlights-along-a-lake-reflecting-mounta", unsplashPhotoId: "photo-1786288675796-49bf4628edbf", photographer: "Martin Leitgeb", photographerUrl: "https://unsplash.com/@martin_leitgeb_photos", photoUrl: "https://unsplash.com/photos/town-with-glowing-streetlights-by-lake-WTmJ13mh8XQ", width: 6192, height: 4128, alt: "A town with glowing streetlights along a lake reflecting mountains under a cool sky" },
  { id: "9M8VrW8cOjY", slug: "body-of-water-between-rocky-cliffs", unsplashPhotoId: "photo-1561317816-7a3e5b2ba6e7", photographer: "Marija L", photographerUrl: "https://unsplash.com/@marliu", photoUrl: "https://unsplash.com/photos/body-of-water-between-rocky-cliffs-9M8VrW8cOjY", width: 6000, height: 4000, alt: "body of water between rocky cliffs" },
  { id: "28T91EzisF8", slug: "birds-eye-view-photography-of-waterfalls", unsplashPhotoId: "photo-1496851002542-2fe43ae0ef15", photographer: "Shawn Appel", photographerUrl: "https://unsplash.com/@shawn_appel", photoUrl: "https://unsplash.com/photos/birds-eye-view-photography-of-waterfalls-28T91EzisF8", width: 3792, height: 2472, alt: "bird's eye view photography of waterfalls" },
  { id: "M4WXK0Bdd5w", slug: "a-view-of-a-waterfall-in-the-middle-of-a-mountain", unsplashPhotoId: "photo-1714045502958-0eb735ca3059", photographer: "Tom Allport", photographerUrl: "https://unsplash.com/@t_mallp_rt", photoUrl: "https://unsplash.com/photos/a-view-of-a-waterfall-in-the-middle-of-a-mountain-M4WXK0Bdd5w", width: 4593, height: 3445, alt: "a view of a waterfall in the middle of a mountain" },
  { id: "6aUcQn1RY58", slug: "rainbow-over-a-powerful-waterfall-with-green-foliage", unsplashPhotoId: "photo-1781041004855-e4d295476391", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/rainbow-over-a-powerful-waterfall-with-green-foliage-6aUcQn1RY58", width: 6000, height: 4000, alt: "Rainbow over a powerful waterfall with green foliage" },
  { id: "AH1Z1ytNOo0", slug: "a-waterfall-in-the-middle-of-a-foggy-day", unsplashPhotoId: "photo-1736633919976-b71ca9bddf08", photographer: "Meg von Haartman", photographerUrl: "https://unsplash.com/@traveleroohlala", photoUrl: "https://unsplash.com/photos/a-waterfall-in-the-middle-of-a-foggy-day-AH1Z1ytNOo0", width: 6000, height: 4000, alt: "A waterfall in the middle of a foggy day" },
  { id: "9ptqGwU-eIw", slug: "waterfall-cascades-through-the-misty-sunny-forest", unsplashPhotoId: "photo-1743836623675-61241d9a0200", photographer: "noelle", photographerUrl: "https://unsplash.com/@noellejlee", photoUrl: "https://unsplash.com/photos/waterfall-cascades-through-the-misty-sunny-forest-9ptqGwU-eIw", width: 5228, height: 4182, alt: "Waterfall cascades through the misty, sunny forest" },
  { id: "Z3TansDffYQ", slug: "the-sun-shines-brightly-on-a-mountain-stream", unsplashPhotoId: "photo-1732654325783-8c6a8b744109", photographer: "Maarten Zaanen", photographerUrl: "https://unsplash.com/@maartenzaanen", photoUrl: "https://unsplash.com/photos/the-sun-shines-brightly-on-a-mountain-stream-Z3TansDffYQ", width: 6000, height: 4000, alt: "The sun shines brightly on a mountain stream" },
  { id: "pes0qHo4Qq8", slug: "a-foggy-mountain-with-a-road-going-through-it", unsplashPhotoId: "photo-1640028828022-460c0b454618", photographer: "Ruta Gudeliene", photographerUrl: "https://unsplash.com/@rutaurban", photoUrl: "https://unsplash.com/photos/a-foggy-mountain-with-a-road-going-through-it-pes0qHo4Qq8", width: 6000, height: 4000, alt: "a foggy mountain with a road going through it" },
  { id: "rtzaJOmXurI", slug: "iceberg-on-water-near-mountain-during-daytime", unsplashPhotoId: "photo-1573995974976-c2407616fe54", photographer: "Visit Greenland", photographerUrl: "https://unsplash.com/@visitgreenland", photoUrl: "https://unsplash.com/photos/iceberg-on-water-near-mountain-during-daytime-rtzaJOmXurI", width: 5397, height: 3603, alt: "iceberg on water near mountain during daytime" },
  { id: "QzDMXDaGUNI", slug: "white-and-brown-mountains-beside-body-of-water", unsplashPhotoId: "photo-1502857700597-4e36edaaa140", photographer: "Jeremy Bishop", photographerUrl: "https://unsplash.com/@jeremybishop", photoUrl: "https://unsplash.com/photos/white-and-brown-mountains-beside-body-of-water-QzDMXDaGUNI", width: 5472, height: 3648, alt: "white and brown mountains beside body of water" },
  { id: "vEz_9XCexU0", slug: "snowy-mountains-meet-the-sea-on-a-cold-day", unsplashPhotoId: "photo-1742301039878-3ec6e0d15078", photographer: "Jacob Castle", photographerUrl: "https://unsplash.com/@jccastle", photoUrl: "https://unsplash.com/photos/snowy-mountains-meet-the-sea-on-a-cold-day-vEz_9XCexU0", width: 6016, height: 3345, alt: "Snowy mountains meet the sea on a cold day" },
  { id: "gtGtmHLNX2U", slug: "man-standing-by-house-during-daytime", unsplashPhotoId: "photo-1551158062-34b7738462d4", photographer: "Drew Dau", photographerUrl: "https://unsplash.com/@daunation", photoUrl: "https://unsplash.com/photos/man-standing-by-house-during-daytime-gtGtmHLNX2U", width: 4000, height: 2250, alt: "man standing by house during daytime" },
  { id: "9uOtPTh-x04", slug: "a-sunset-over-a-beach", unsplashPhotoId: "photo-1667759317132-53c2320578de", photographer: "Karla Robinson", photographerUrl: "https://unsplash.com/@karlarobinson", photoUrl: "https://unsplash.com/photos/a-sunset-over-a-beach-9uOtPTh-x04", width: 4272, height: 2848, alt: "a sunset over a beach" },
  { id: "pdRyFq73lJY", slug: "a-man-in-a-white-space-suit-holding-a-red-substance", unsplashPhotoId: "photo-1586999082807-3e0bc859ab73", photographer: "Bradley Dunn", photographerUrl: "https://unsplash.com/@bradleycdunn", photoUrl: "https://unsplash.com/photos/a-man-in-a-white-space-suit-holding-a-red-substance-pdRyFq73lJY", width: 5800, height: 3872, alt: "a man in a white space suit holding a red substance" },
  { id: "PBjaRY5jfr0", slug: "blue-hot-air-balloon-on-sky", unsplashPhotoId: "photo-1595265561094-bf41f3ef42ac", photographer: "Natalya Letunova", photographerUrl: "https://unsplash.com/@naletu", photoUrl: "https://unsplash.com/photos/blue-hot-air-balloon-on-sky-PBjaRY5jfr0", width: 3992, height: 2992, alt: "blue hot air balloon on sky" },
  { id: "WE8mfKIPHpQ", slug: "aerial-photography-of-mountain-vallet", unsplashPhotoId: "photo-1444752176289-a22f853cb706", photographer: "Ana Ib", photographerUrl: "https://unsplash.com/@serviam500", photoUrl: "https://unsplash.com/photos/aerial-photography-of-mountain-vallet-WE8mfKIPHpQ", width: 3264, height: 2448, alt: "aerial photography of mountain vallet" },
  { id: "Qf73V_zqdEQ", slug: "aerial-view-of-a-town-seen-through-clouds", unsplashPhotoId: "photo-1770697951227-d651feb532f1", photographer: "Jun Ren", photographerUrl: "https://unsplash.com/@renjunn", photoUrl: "https://unsplash.com/photos/aerial-view-of-a-town-seen-through-clouds-Qf73V_zqdEQ", width: 5184, height: 3456, alt: "Aerial view of a town seen through clouds" },
  { id: "iN9tSC2mF5U", slug: "a-lone-horse-standing-in-a-field-of-grass", unsplashPhotoId: "photo-1714552815828-22d8b675d54b", photographer: "Marko Lengyel", photographerUrl: "https://unsplash.com/@marko_lengyel", photoUrl: "https://unsplash.com/photos/a-lone-horse-standing-in-a-field-of-grass-iN9tSC2mF5U", width: 6000, height: 4000, alt: "a lone horse standing in a field of grass" },
];

export function photoBySlug(slug: string): Photo | undefined {
  return PHOTOS.find((photo) => photo.slug === slug);
}

export function photoStandardSrc(photo: Photo, width: (typeof PHOTO_SRC_WIDTHS)[number] = 1280): string {
  return `${PHOTO_STORAGE_BASE_URL}/photos/${photo.slug}/standard-${width}.jpg`;
}

export function photoStandardSrcset(photo: Photo): string {
  return PHOTO_SRC_WIDTHS
    .filter(w => w <= photo.width)
    .map(w => `${PHOTO_STORAGE_BASE_URL}/photos/${photo.slug}/standard-${w}.jpg ${w}w`)
    .join(", ");
}

export function photoGainmapSrc(photo: Photo, width: (typeof PHOTO_SRC_WIDTHS)[number] = 1280): string {
  return `${PHOTO_STORAGE_BASE_URL}/photos/${photo.slug}/gainmap-${width}.jpg`;
}

export function photoGainmapSrcset(photo: Photo): string {
  return PHOTO_SRC_WIDTHS
    .filter(w => w <= photo.width)
    .map(w => `${PHOTO_STORAGE_BASE_URL}/photos/${photo.slug}/gainmap-${w}.jpg ${w}w`)
    .join(", ");
}

export function withUnsplashReferral(url: string): string {
  const join = url.includes("?") ? "&" : "?";
  return `${url}${join}utm_source=gainmaps&utm_medium=referral`;
}

export function photosPageCount(): number {
  return Math.ceil(PHOTOS.length / PAGE_SIZE);
}

export function photosForPage(page: number): readonly Photo[] {
  const total = photosPageCount();
  const current = Math.min(Math.max(page, 1), Math.max(total, 1));
  const start = (current - 1) * PAGE_SIZE;
  return PHOTOS.slice(start, start + PAGE_SIZE);
}

export function clampPhotoPage(page: number): number {
  const total = photosPageCount();
  if (!Number.isFinite(page) || page < 1) return 1;
  return Math.min(Math.floor(page), Math.max(total, 1));
}
