/**
 * 100 Unsplash photographs for /photos. Standard tiles hotlink the CDN;
 * Ultra tiles are local gain map JPEGs at /photos/{slug}/gainmap.jpg (boost 1.0 max).
 * Responsive variants: gainmap-400.jpg, gainmap-800.jpg, gainmap-1280.jpg.
 *
 * Rebuild Ultra files: npx tsx tools/photos/build-photos.ts
 */
export type Photo = {
  readonly id: string;
  readonly slug: string;
  /** images.unsplash.com filename, e.g. photo-1506905925346-21bda4d32df4 */
  readonly unsplashPhotoId: string;
  readonly photographer: string;
  readonly photographerUrl: string;
  readonly photoUrl: string;
  readonly width: number;
  readonly height: number;
  readonly alt: string;
};

export const PAGE_SIZE = 12;

export const PHOTOS: readonly Photo[] = [
  { id: "zmA2gYoK844", slug: "green-pine-trees", unsplashPhotoId: "photo-1562605270-3cdc52af7f5d", photographer: "Ethan Dow", photographerUrl: "https://unsplash.com/@ethandow", photoUrl: "https://unsplash.com/photos/green-pine-trees-zmA2gYoK844", width: 1900, height: 3040, alt: "green pine trees" },
  { id: "9bBEDfzbDc4", slug: "a-clear-chunk-of-ice-on-a-dark-pebble-beach-near-the-ocean", unsplashPhotoId: "photo-1787238347746-44391edcfa32", photographer: "Benjamin Chambon", photographerUrl: "https://unsplash.com/@benjamin_photo_lab", photoUrl: "https://unsplash.com/photos/ice-chunk-on-dark-pebble-beach-9bBEDfzbDc4", width: 4000, height: 6000, alt: "A clear chunk of ice on a dark pebble beach near the ocean" },
  { id: "qsdkMlbfne4", slug: "a-seal-rests-on-a-shallow-sandbar-in-calm-water", unsplashPhotoId: "photo-1784978516675-8daa424836f5", photographer: "Jeremy Hynes", photographerUrl: "https://unsplash.com/@hynesight", photoUrl: "https://unsplash.com/photos/a-seal-rests-on-a-shallow-sandbar-in-calm-water-qsdkMlbfne4", width: 7660, height: 3830, alt: "A seal rests on a shallow sandbar in calm water" },
  { id: "-PvICnpWGlc", slug: "two-people-on-a-rocky-cliff-overlooking-a-valley-under-a-low", unsplashPhotoId: "photo-1787055923390-67a2dbac36b0", photographer: "Michael Shtern", photographerUrl: "https://unsplash.com/@mic222", photoUrl: "https://unsplash.com/photos/people-on-rocky-cliff-at-valley--PvICnpWGlc", width: 6720, height: 3780, alt: "Two people on a rocky cliff overlooking a valley under a low sun" },
  { id: "-zrRKebyM8c", slug: "turquoise-river-flows-through-a-dramatic-rocky-canyon", unsplashPhotoId: "photo-1785131455100-7f15d21ebffe", photographer: "Mahyar Yeganeh", photographerUrl: "https://unsplash.com/@nvamahyar", photoUrl: "https://unsplash.com/photos/turquoise-river-flows-through-a-dramatic-rocky-canyon--zrRKebyM8c", width: 3024, height: 4032, alt: "Turquoise river flows through a dramatic, rocky canyon" },
  { id: "I8uRAuI5JF4", slug: "a-black-dog-on-a-rock-with-colorful-mountains", unsplashPhotoId: "photo-1778701985068-4561674b45d8", photographer: "Ahmed", photographerUrl: "https://unsplash.com/@mutecevvil", photoUrl: "https://unsplash.com/photos/a-black-dog-on-a-rock-with-colorful-mountains-I8uRAuI5JF4", width: 4583, height: 6874, alt: "A black dog on a rock with colorful mountains" },
  { id: "l3Pvd4M3Css", slug: "low-sun-with-lens-flare-over-a-forested-valley-and-granite-c", unsplashPhotoId: "photo-1787170426598-858e57c774dd", photographer: "Priyank Pathak", photographerUrl: "https://unsplash.com/@ppriyank", photoUrl: "https://unsplash.com/photos/low-sun-over-yosemite-valley-cliffs-l3Pvd4M3Css", width: 9459, height: 5475, alt: "Low sun with lens flare over a forested valley and granite cliffs in Yosemite" },
  { id: "maKSDW4Ucoc", slug: "a-person-walks-along-a-desert-sand-dune-at-sunset", unsplashPhotoId: "photo-1781902834540-4604713b7e1b", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/a-person-walks-along-a-desert-sand-dune-at-sunset-maKSDW4Ucoc", width: 3525, height: 5287, alt: "A person walks along a desert sand dune at sunset" },
  { id: "ygRIDv3W6Ec", slug: "zebras-in-a-golden-sunlit-grassy-field", unsplashPhotoId: "photo-1781730655215-63a2a92623e4", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/zebras-in-a-golden-sunlit-grassy-field-ygRIDv3W6Ec", width: 5713, height: 3809, alt: "Zebras in a golden, sunlit grassy field" },
  { id: "qsQNjjHjFns", slug: "striking-layered-desert-mountain-under-a-beautiful-sunset-sk", unsplashPhotoId: "photo-1785142893888-58e3954672db", photographer: "Kilic-Emre Akdag", photographerUrl: "https://unsplash.com/@kilicemre7007", photoUrl: "https://unsplash.com/photos/striking-layered-desert-mountain-under-a-beautiful-sunset-sky-qsQNjjHjFns", width: 4024, height: 3018, alt: "Striking layered desert mountain under a beautiful sunset sky" },
  { id: "i_J0c5m6yvc", slug: "a-person-in-a-red-cloak-on-a-vast-sand-dune-at-golden-hour", unsplashPhotoId: "photo-1786300412449-875316124ba1", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/person-in-red-cloak-on-sand-dune-i_J0c5m6yvc", width: 4382, height: 6573, alt: "A person in a red cloak on a vast sand dune at golden hour" },
  { id: "j0M14wYc1_A", slug: "wooden-cabin-in-a-lush-green-meadow-before-a-mountain", unsplashPhotoId: "photo-1784019226271-f89c21f7791a", photographer: "Yousef Salhamoud", photographerUrl: "https://unsplash.com/@salhamoud", photoUrl: "https://unsplash.com/photos/wooden-cabin-in-a-lush-green-meadow-before-a-mountain-j0M14wYc1_A", width: 4470, height: 6705, alt: "Wooden cabin in a lush green meadow before a mountain" },
  { id: "s2F_H5M7-Vs", slug: "yellow-house-with-wooden-shutters-and-mountain-in-background", unsplashPhotoId: "photo-1785739125961-0c316bc80d13", photographer: "Arjun Raj", photographerUrl: "https://unsplash.com/@mr_hell", photoUrl: "https://unsplash.com/photos/yellow-house-with-wooden-shutters-and-mountain-in-background-s2F_H5M7-Vs", width: 5949, height: 3347, alt: "Yellow house with wooden shutters and mountain in background" },
  { id: "ttMdFEwlayw", slug: "a-person-looking-out-over-a-lake-and-mountains-from-a-metal", unsplashPhotoId: "photo-1786813478692-b6df54dc3f6c", photographer: "Dawid Tkocz", photographerUrl: "https://unsplash.com/@dawidtkocz", photoUrl: "https://unsplash.com/photos/person-overlooking-lake-and-mountains-ttMdFEwlayw", width: 3840, height: 2560, alt: "A person looking out over a lake and mountains from a metal railing" },
  { id: "Yh3alvVRvRA", slug: "people-on-a-grassy-hillside-with-a-wooden-mountain-hut-below", unsplashPhotoId: "photo-1787224641466-9195e22b85b7", photographer: "Mattia Revelant", photographerUrl: "https://unsplash.com/@vez02", photoUrl: "https://unsplash.com/photos/people-on-grassy-mountain-hillside-Yh3alvVRvRA", width: 6240, height: 4160, alt: "People on a grassy hillside with a wooden mountain hut below rocky peaks" },
  { id: "ImKtzwJRBN0", slug: "historic-white-church-building-on-a-sandy-dune-landscape", unsplashPhotoId: "photo-1780656093756-0faf1a88159f", photographer: "Max Böhme", photographerUrl: "https://unsplash.com/@max_boehme", photoUrl: "https://unsplash.com/photos/historic-white-church-building-on-a-sandy-dune-landscape-ImKtzwJRBN0", width: 4495, height: 6743, alt: "Historic white church building on a sandy dune landscape" },
  { id: "CpVwilODVaI", slug: "a-turquoise-volcanic-crater-lake-surrounded-by-rocky-cliffs", unsplashPhotoId: "photo-1786288042250-1258f5839eaf", photographer: "Rowan Heuvel", photographerUrl: "https://unsplash.com/@insolitus", photoUrl: "https://unsplash.com/photos/turquoise-volcanic-crater-lake-CpVwilODVaI", width: 8192, height: 5464, alt: "A turquoise volcanic crater lake surrounded by rocky cliffs under a soft pink sky" },
  { id: "f8FgfDNLg2A", slug: "full-moon-in-a-clear-blue-sky-above-buildings", unsplashPhotoId: "photo-1773587040541-6d43f9ae5595", photographer: "Jones Lee", photographerUrl: "https://unsplash.com/@art0819leo", photoUrl: "https://unsplash.com/photos/full-moon-in-a-clear-blue-sky-above-buildings-f8FgfDNLg2A", width: 6000, height: 4500, alt: "Full moon in a clear blue sky above buildings" },
  { id: "nVxsqVi3hrk", slug: "a-solitary-egret-stands-in-misty-morning-light-by-reeds", unsplashPhotoId: "photo-1769257423963-36ed2d94d45b", photographer: "Bob Brewer", photographerUrl: "https://unsplash.com/@brewbottle", photoUrl: "https://unsplash.com/photos/a-solitary-egret-stands-in-misty-morning-light-by-reeds-nVxsqVi3hrk", width: 5281, height: 3213, alt: "A solitary egret stands in misty morning light by reeds" },
  { id: "Yh88Ag5d98M", slug: "silhouettes-of-people-against-a-bright-low-sun-in-a-clear-sk", unsplashPhotoId: "photo-1786962730761-cf13c9b7c360", photographer: "Oleksii Tsaryuk", photographerUrl: "https://unsplash.com/@photobyredder", photoUrl: "https://unsplash.com/photos/people-silhouettes-against-low-sun-Yh88Ag5d98M", width: 6000, height: 4000, alt: "Silhouettes of people against a bright low sun in a clear sky" },
  { id: "SJTO3-MTpBA", slug: "a-silhouette-stands-before-a-cloudy-sunset", unsplashPhotoId: "photo-1752978951972-a8f8d578046e", photographer: "Atul Pandey", photographerUrl: "https://unsplash.com/@iatulp", photoUrl: "https://unsplash.com/photos/a-silhouette-stands-before-a-cloudy-sunset-SJTO3-MTpBA", width: 2469, height: 3292, alt: "A silhouette stands before a cloudy sunset" },
  { id: "Gt_ZeRJ7ETo", slug: "a-beautiful-coastline-with-mountains-and-boats", unsplashPhotoId: "photo-1754532432708-4bf134683082", photographer: "Gatot Adri", photographerUrl: "https://unsplash.com/@garakta", photoUrl: "https://unsplash.com/photos/a-beautiful-coastline-with-mountains-and-boats-Gt_ZeRJ7ETo", width: 2688, height: 4032, alt: "A beautiful coastline with mountains and boats" },
  { id: "twukN12EN7c", slug: "landscape-photography-of-mountains", unsplashPhotoId: "photo-1500964757637-c85e8a162699", photographer: "simon", photographerUrl: "https://unsplash.com/@simon_berger", photoUrl: "https://unsplash.com/photos/landscape-photography-of-mountains-twukN12EN7c", width: 4608, height: 2963, alt: "landscape photography of mountains" },
  { id: "ibikgDapcp4", slug: "layered-mountain-ridges-under-a-warm-orange-sky-with-long-shado", unsplashPhotoId: "photo-1604223190546-a43e4c7f29d7", photographer: "Sven Pieren", photographerUrl: "https://unsplash.com/@sven_pieren", photoUrl: "https://unsplash.com/photos/mountain-ridges-under-warm-sky-ibikgDapcp4", width: 6016, height: 4016, alt: "Layered mountain ridges under a warm orange sky with long shadows" },
  { id: "I_n_b44cqhk", slug: "green-mountains-under-blue-sky-during-daytime", unsplashPhotoId: "photo-1612441804231-77a36b284856", photographer: "Simon Lohmann", photographerUrl: "https://unsplash.com/@slohmann", photoUrl: "https://unsplash.com/photos/green-mountains-under-blue-sky-during-daytime-I_n_b44cqhk", width: 6720, height: 4480, alt: "green mountains under blue sky during daytime" },
  { id: "6yPiMRZzFH0", slug: "green-grass-field-near-green-trees-and-mountains-during-daytime", unsplashPhotoId: "photo-1601281426795-9fedf41df8d1", photographer: "Shafagh Faridifar", photographerUrl: "https://unsplash.com/@shafagh58", photoUrl: "https://unsplash.com/photos/green-grass-field-near-green-trees-and-mountains-during-daytime-6yPiMRZzFH0", width: 4000, height: 3000, alt: "green grass field near green trees and mountains during daytime" },
  { id: "xJ2tjuUHD9M", slug: "mountain-dew-during-sunrise", unsplashPhotoId: "photo-1444927714506-8492d94b4e3d", photographer: "Paul Earle", photographerUrl: "https://unsplash.com/@paulearlephotography", photoUrl: "https://unsplash.com/photos/mountain-dew-during-sunrise-xJ2tjuUHD9M", width: 3000, height: 1987, alt: "mountain dew during sunrise" },
  { id: "M6XC789HLe8", slug: "snow-dusted-granite-cliffs-and-a-waterfall-above-a-forest-in-yo", unsplashPhotoId: "photo-1498429089284-41f8cf3ffd39", photographer: "Aniket Deole", photographerUrl: "https://unsplash.com/@anik3t", photoUrl: "https://unsplash.com/photos/granite-cliffs-and-waterfall-in-yosemite-M6XC789HLe8", width: 7952, height: 5304, alt: "Snow-dusted granite cliffs and a waterfall above a forest in Yosemite National Park" },
  { id: "rj6P1M_fz6M", slug: "brown-rocky-mountain-under-white-clouds-and-blue-sky-during-day", unsplashPhotoId: "photo-1611080402167-ed75bae6df32", photographer: "Florian Schönbrunner", photographerUrl: "https://unsplash.com/@ferdinand8a", photoUrl: "https://unsplash.com/photos/brown-rocky-mountain-under-white-clouds-and-blue-sky-during-daytime-rj6P1M_fz6M", width: 5184, height: 3456, alt: "brown rocky mountain under white clouds and blue sky during daytime" },
  { id: "PdGBci-4jR8", slug: "view-of-mountain", unsplashPhotoId: "photo-1552152370-fb05b25ff17d", photographer: "Alessio Soggetti", photographerUrl: "https://unsplash.com/@asoggetti", photoUrl: "https://unsplash.com/photos/view-of-mountain-PdGBci-4jR8", width: 4970, height: 3318, alt: "view of mountain" },
  { id: "v1nLZZfQ-d8", slug: "a-scenic-view-of-a-mountain-range-with-green-mountains-in-the-b", unsplashPhotoId: "photo-1516825994218-b2d93290b0fd", photographer: "Jacek Dylag", photographerUrl: "https://unsplash.com/@dylu", photoUrl: "https://unsplash.com/photos/a-scenic-view-of-a-mountain-range-with-green-mountains-in-the-background-v1nLZZfQ-d8", width: 7360, height: 4912, alt: "a scenic view of a mountain range with green mountains in the background" },
  { id: "k6GpdsPJSZw", slug: "aerial-photography-of-mountains", unsplashPhotoId: "photo-1548679847-1d4ff48016c7", photographer: "Fabrizio Conti", photographerUrl: "https://unsplash.com/@conti_photos", photoUrl: "https://unsplash.com/photos/aerial-photography-of-mountains-k6GpdsPJSZw", width: 5402, height: 3601, alt: "aerial photography of mountains" },
  { id: "s-y2HJElONo", slug: "green-grass-field-and-mountains-under-white-clouds-and-blue-sky", unsplashPhotoId: "photo-1610552050890-fe99536c2615", photographer: "lucas wesney", photographerUrl: "https://unsplash.com/@wesnext", photoUrl: "https://unsplash.com/photos/green-grass-field-and-mountains-under-white-clouds-and-blue-sky-during-daytime-s-y2HJElONo", width: 7891, height: 5051, alt: "green grass field and mountains under white clouds and blue sky during daytime" },
  { id: "-g7axSVst6Y", slug: "landscape-photography-of-mountain-ranges-under-purple-and-pink", unsplashPhotoId: "photo-1466854076813-4aa9ac0fc347", photographer: "Štefan Štefančík", photographerUrl: "https://unsplash.com/@cikstefan", photoUrl: "https://unsplash.com/photos/landscape-photography-of-mountain-ranges-under-purple-and-pink-skies--g7axSVst6Y", width: 2400, height: 1350, alt: "landscape photography of mountain ranges under purple and pink skies" },
  { id: "rQqWOHZ96OM", slug: "snow-capped-mountains-at-daytime", unsplashPhotoId: "photo-1515268064940-5150b7c29f35", photographer: "John Rodenn Castillo", photographerUrl: "https://unsplash.com/@nightcrawler1986", photoUrl: "https://unsplash.com/photos/snow-capped-mountains-at-daytime-rQqWOHZ96OM", width: 3888, height: 2592, alt: "snow capped mountains at daytime" },
  { id: "V1NVvXmO_dk", slug: "mountains-with-fog", unsplashPhotoId: "photo-1573126617899-41f1dffb196c", photographer: "Konstantin Kleine", photographerUrl: "https://unsplash.com/@konstantinkleine", photoUrl: "https://unsplash.com/photos/mountains-with-fog-V1NVvXmO_dk", width: 5616, height: 3744, alt: "mountains with fog" },
  { id: "U8FEzONZCsg", slug: "green-grass-field-in-the-mountain", unsplashPhotoId: "photo-1495710388177-22c73fa5f84e", photographer: "Etienne Delorieux", photographerUrl: "https://unsplash.com/@etiennedelorieux", photoUrl: "https://unsplash.com/photos/green-grass-field-in-the-mountain-U8FEzONZCsg", width: 3872, height: 2592, alt: "green grass field in the mountain" },
  { id: "x-XwnC7FgFM", slug: "silhouette-of-mountains-during-daytime", unsplashPhotoId: "photo-1612676239016-41e2c92b8e06", photographer: "Pinal Jain", photographerUrl: "https://unsplash.com/@pinaljain1993", photoUrl: "https://unsplash.com/photos/silhouette-of-mountains-during-daytime-x-XwnC7FgFM", width: 6000, height: 4000, alt: "silhouette of mountains during daytime" },
  { id: "1YQDhLtB9yU", slug: "green-trees-and-snow-covered-mountains-during-daytime", unsplashPhotoId: "photo-1604428803896-c1e5151d4128", photographer: "Hendrik Kespohl", photographerUrl: "https://unsplash.com/@hendrikkay", photoUrl: "https://unsplash.com/photos/green-trees-and-snow-covered-mountains-during-daytime-1YQDhLtB9yU", width: 5184, height: 3456, alt: "green trees and snow covered mountains during daytime" },
  { id: "YKN_G9L9nMA", slug: "a-mountain-valley-in-north-cascades-national-park-under-a-warm", unsplashPhotoId: "photo-1584148721201-b6432e0d5106", photographer: "Toan Chu", photographerUrl: "https://unsplash.com/@toanchu", photoUrl: "https://unsplash.com/photos/mountain-valley-in-north-cascades-YKN_G9L9nMA", width: 7952, height: 5304, alt: "A mountain valley in North Cascades National Park under a warm golden sky" },
  { id: "pl1mhwMctJc", slug: "red-tent-on-grass-field-beside-ice-capped-mountain-nature-photo", unsplashPhotoId: "photo-1464547323744-4edd0cd0c746", photographer: "Dino Reichmuth", photographerUrl: "https://unsplash.com/@dinoreichmuth", photoUrl: "https://unsplash.com/photos/red-tent-on-grass-field-beside-ice-capped-mountain-nature-photography-pl1mhwMctJc", width: 5616, height: 3744, alt: "red tent on grass field beside ice capped mountain nature photography" },
  { id: "1o4Z1EwCkaY", slug: "black-mountain-covered-by-snow", unsplashPhotoId: "photo-1533135404995-a618910b7b6f", photographer: "Neil Rosenstech", photographerUrl: "https://unsplash.com/@neilrst", photoUrl: "https://unsplash.com/photos/black-mountain-covered-by-snow-1o4Z1EwCkaY", width: 6016, height: 4016, alt: "black mountain covered by snow" },
  { id: "a562ZEFKW8I", slug: "photo-of-mountain-alps", unsplashPhotoId: "photo-1473984951266-787b955c9e0b", photographer: "Aleksandar Jason", photographerUrl: "https://unsplash.com/@aleksandarjason", photoUrl: "https://unsplash.com/photos/photo-of-mountain-alps-a562ZEFKW8I", width: 5760, height: 3840, alt: "photo of mountain alps" },
  { id: "HbhJyWnE9Oo", slug: "aerial-photo-of-brown-mountain-under-gray-sky", unsplashPhotoId: "photo-1445452916036-9022dfd33aa8", photographer: "Michał Parzuchowski", photographerUrl: "https://unsplash.com/@mparzuchowski", photoUrl: "https://unsplash.com/photos/aerial-photo-of-brown-mountain-under-gray-sky-HbhJyWnE9Oo", width: 4672, height: 3104, alt: "aerial photo of brown mountain under gray sky" },
  { id: "OZACaaUskhg", slug: "aerial-view-photography-of-trees-and-mountains", unsplashPhotoId: "photo-1477948879622-5f16e220fa42", photographer: "Olivier Miche", photographerUrl: "https://unsplash.com/@oliviermiche", photoUrl: "https://unsplash.com/photos/aerial-view-photography-of-trees-and-mountains-OZACaaUskhg", width: 6958, height: 4644, alt: "aerial view photography of trees and mountains" },
  { id: "gdE-5Oui1Y0", slug: "mountains-covered-with-fogs", unsplashPhotoId: "photo-1508108712903-49b7ef9b1df8", photographer: "Alessio Soggetti", photographerUrl: "https://unsplash.com/@asoggetti", photoUrl: "https://unsplash.com/photos/mountains-covered-with-fogs-gdE-5Oui1Y0", width: 5832, height: 3893, alt: "mountains covered with fogs" },
  { id: "wVjd0eWNqI8", slug: "mountains-cover-by-fogs", unsplashPhotoId: "photo-1483354483454-4cd359948304", photographer: "Paul Earle", photographerUrl: "https://unsplash.com/@paulearlephotography", photoUrl: "https://unsplash.com/photos/mountains-cover-by-fogs-wVjd0eWNqI8", width: 3000, height: 2002, alt: "mountains cover by fogs" },
  { id: "evJh_sTH0b8", slug: "snow-covered-mountain-under-blue-sky-during-night-time", unsplashPhotoId: "photo-1612539473441-dfc1cefd5e1e", photographer: "Renato Muolo", photographerUrl: "https://unsplash.com/@muolor", photoUrl: "https://unsplash.com/photos/snow-covered-mountain-under-blue-sky-during-night-time-evJh_sTH0b8", width: 5878, height: 3922, alt: "snow covered mountain under blue sky during night time" },
  { id: "7L9QtwXOhQU", slug: "green-and-brown-mountain-under-blue-sky-during-daytime", unsplashPhotoId: "photo-1598858715214-3d0f6219e267", photographer: "Artur Stanulevich", photographerUrl: "https://unsplash.com/@artstanulevich", photoUrl: "https://unsplash.com/photos/green-and-brown-mountain-under-blue-sky-during-daytime-7L9QtwXOhQU", width: 5184, height: 3456, alt: "green and brown mountain under blue sky during daytime" },
  { id: "NuBvAE6VfSM", slug: "black-and-white-mountains-under-white-sky-during-daytime", unsplashPhotoId: "photo-1609342122563-a43ac8917a3a", photographer: "Tobias Rademacher", photographerUrl: "https://unsplash.com/@tobbes_rd", photoUrl: "https://unsplash.com/photos/black-and-white-mountains-under-white-sky-during-daytime-NuBvAE6VfSM", width: 6316, height: 4211, alt: "black and white mountains under white sky during daytime" },
  { id: "eYg1BXfToXc", slug: "green-grass-field-and-mountain-under-blue-sky-during-daytime", unsplashPhotoId: "photo-1620414476107-2188707d780b", photographer: "Ana M.", photographerUrl: "https://unsplash.com/@anamandic", photoUrl: "https://unsplash.com/photos/green-grass-field-and-mountain-under-blue-sky-during-daytime-eYg1BXfToXc", width: 3936, height: 2952, alt: "green grass field and mountain under blue sky during daytime" },
  { id: "tKyt-GZowHQ", slug: "field-of-brown-grasses-within-mountain-range", unsplashPhotoId: "photo-1446488614340-2d1a68d662f9", photographer: "Keghan Crossland", photographerUrl: "https://unsplash.com/@keghancphoto", photoUrl: "https://unsplash.com/photos/field-of-brown-grasses-within-mountain-range-tKyt-GZowHQ", width: 4240, height: 2832, alt: "field of brown grasses within mountain range" },
  { id: "P1dGwlSJiE8", slug: "red-parachute-above-green-trees-at-daytime", unsplashPhotoId: "photo-1456139333202-745e9029f0ef", photographer: "Maurice Smeets", photographerUrl: "https://unsplash.com/@mauricesmeets", photoUrl: "https://unsplash.com/photos/red-parachute-above-green-trees-at-daytime-P1dGwlSJiE8", width: 5184, height: 3456, alt: "red parachute above green trees at daytime" },
  { id: "mkdI8JN6sDU", slug: "grey-and-white-mountain", unsplashPhotoId: "photo-1469212044023-0e55b4b9745a", photographer: "Matheus Bandoch", photographerUrl: "https://unsplash.com/@mbandoch", photoUrl: "https://unsplash.com/photos/grey-and-white-mountain-mkdI8JN6sDU", width: 4928, height: 3264, alt: "grey and white mountain" },
  { id: "boTqoTtqtYY", slug: "brown-and-white-mountains-under-blue-sky-during-daytime", unsplashPhotoId: "photo-1597216394928-e6bc38109801", photographer: "S&B Vonlanthen", photographerUrl: "https://unsplash.com/@blavon", photoUrl: "https://unsplash.com/photos/brown-and-white-mountains-under-blue-sky-during-daytime-boTqoTtqtYY", width: 6016, height: 4016, alt: "brown and white mountains under blue sky during daytime" },
  { id: "Vz6g5tT-28c", slug: "aerial-photography-of-glacier-mountains", unsplashPhotoId: "photo-1530631045516-a797dbaabd14", photographer: "Fabrizio Conti", photographerUrl: "https://unsplash.com/@conti_photos", photoUrl: "https://unsplash.com/photos/aerial-photography-of-glacier-mountains-Vz6g5tT-28c", width: 5472, height: 3648, alt: "aerial photography of glacier mountains" },
  { id: "0iOXuu2GGUM", slug: "a-grassy-field-with-a-mountain-in-the-background", unsplashPhotoId: "photo-1643984009272-3879e788dcf1", photographer: "Micael Rodrigues", photographerUrl: "https://unsplash.com/@micaelrodrigues", photoUrl: "https://unsplash.com/photos/a-grassy-field-with-a-mountain-in-the-background-0iOXuu2GGUM", width: 4000, height: 1800, alt: "a grassy field with a mountain in the background" },
  { id: "PwzISwC2kLs", slug: "mountains-covered-with-fogs-pwziswc2", unsplashPhotoId: "photo-1542708993627-b6e5bbae43c4", photographer: "Arindam Saha", photographerUrl: "https://unsplash.com/@hyperickz", photoUrl: "https://unsplash.com/photos/mountains-covered-with-fogs-PwzISwC2kLs", width: 5635, height: 3875, alt: "mountains covered with fogs" },
  { id: "F1oeYBKJsdw", slug: "wheat-field-near-pine-trees-beside-mountains-under-blue-and-whi", unsplashPhotoId: "photo-1446488547543-78c11468449a", photographer: "Keghan Crossland", photographerUrl: "https://unsplash.com/@keghancphoto", photoUrl: "https://unsplash.com/photos/wheat-field-near-pine-trees-beside-mountains-under-blue-and-white-sky-F1oeYBKJsdw", width: 4240, height: 2832, alt: "wheat field near pine trees beside mountains under blue and white sky" },
  { id: "WavTEdCDJ2g", slug: "green-grass-field-near-lake-and-mountains-under-white-clouds-an", unsplashPhotoId: "photo-1608820980073-0a946a135983", photographer: "Lyndsey Dulfer", photographerUrl: "https://unsplash.com/@lyndseydulfer", photoUrl: "https://unsplash.com/photos/green-grass-field-near-lake-and-mountains-under-white-clouds-and-blue-sky-during-daytime-WavTEdCDJ2g", width: 4032, height: 3024, alt: "green grass field near lake and mountains under white clouds and blue sky during daytime" },
  { id: "fNCT47HnlNE", slug: "grayscale-photo-of-snow-covered-mountain", unsplashPhotoId: "photo-1569951707784-04494c5ed864", photographer: "Jan Kronies", photographerUrl: "https://unsplash.com/@jankronies", photoUrl: "https://unsplash.com/photos/grayscale-photo-of-snow-covered-mountain-fNCT47HnlNE", width: 5081, height: 3219, alt: "grayscale photo of snow covered mountain" },
  { id: "M6_OMo2bTvI", slug: "brown-and-white-mountains-under-blue-sky-during-da-m6omo2bt", unsplashPhotoId: "photo-1615213780624-97494a577778", photographer: "Rodri Caruso", photographerUrl: "https://unsplash.com/@rodricaruso", photoUrl: "https://unsplash.com/photos/brown-and-white-mountains-under-blue-sky-during-daytime-M6_OMo2bTvI", width: 5184, height: 3456, alt: "brown and white mountains under blue sky during daytime" },
  { id: "EFvP9cHipMQ", slug: "silhouette-of-mountains-covered-with-fog", unsplashPhotoId: "photo-1444065707204-12decac917e8", photographer: "Michał Parzuchowski", photographerUrl: "https://unsplash.com/@mparzuchowski", photoUrl: "https://unsplash.com/photos/silhouette-of-mountains-covered-with-fog-EFvP9cHipMQ", width: 4672, height: 3104, alt: "silhouette of mountains covered with fog" },
  { id: "EhnHNsHl3sU", slug: "a-lake-in-the-middle-of-a-mountain-range", unsplashPhotoId: "photo-1699786023101-2181d624d234", photographer: "Yevhenii Dubrovskyi", photographerUrl: "https://unsplash.com/@dbr0vskyi", photoUrl: "https://unsplash.com/photos/a-lake-in-the-middle-of-a-mountain-range-EhnHNsHl3sU", width: 7008, height: 4672, alt: "a lake in the middle of a mountain range" },
  { id: "-3Z-DiGK0hA", slug: "green-mountain-across-thick-white-clouds-photo", unsplashPhotoId: "photo-1563791877359-4a03fb576945", photographer: "Gaétan Meyer", photographerUrl: "https://unsplash.com/@cinquantesix", photoUrl: "https://unsplash.com/photos/green-mountain-across-thick-white-clouds-photo--3Z-DiGK0hA", width: 5000, height: 4000, alt: "green mountain across thick white clouds photo" },
  { id: "6h24vYjveXg", slug: "brown-and-white-mountain-under-cloudy-sky-during-daytime", unsplashPhotoId: "photo-1625647891375-91463187659f", photographer: "FUTC", photographerUrl: "https://unsplash.com/@futc", photoUrl: "https://unsplash.com/photos/brown-and-white-mountain-under-cloudy-sky-during-daytime-6h24vYjveXg", width: 7952, height: 5304, alt: "brown and white mountain under cloudy sky during daytime" },
  { id: "T0PaR22Kv8k", slug: "a-view-of-a-body-of-water-from-a-hill", unsplashPhotoId: "photo-1707007785777-9324ce8cf42d", photographer: "Phill Brown", photographerUrl: "https://unsplash.com/@phillbrown", photoUrl: "https://unsplash.com/photos/a-view-of-a-body-of-water-from-a-hill-T0PaR22Kv8k", width: 5970, height: 3980, alt: "a view of a body of water from a hill" },
  { id: "S7YTvzJnf0w", slug: "a-view-of-a-beach-with-waves-coming-in-to-shore", unsplashPhotoId: "photo-1707007730851-c53cc2879f00", photographer: "Phill Brown", photographerUrl: "https://unsplash.com/@phillbrown", photoUrl: "https://unsplash.com/photos/a-view-of-a-beach-with-waves-coming-in-to-shore-S7YTvzJnf0w", width: 5224, height: 3483, alt: "a view of a beach with waves coming in to shore" },
  { id: "eh3kB7wAJgs", slug: "a-vast-expanse-of-deep-blue-ocean-under-a-bright-sky-with-scatt", unsplashPhotoId: "photo-1468324187476-c4e804213545", photographer: "Stephen Crowley", photographerUrl: "https://unsplash.com/@crowleystephen", photoUrl: "https://unsplash.com/photos/ocean-under-bright-cloudy-sky-eh3kB7wAJgs", width: 5944, height: 3952, alt: "A vast expanse of deep blue ocean under a bright sky with scattered clouds" },
  { id: "imyLjNyR6Jk", slug: "a-large-body-of-water-sitting-under-a-blue-sky", unsplashPhotoId: "photo-1645450277772-fd5884921748", photographer: "Tiago Muraro", photographerUrl: "https://unsplash.com/@tiago", photoUrl: "https://unsplash.com/photos/a-large-body-of-water-sitting-under-a-blue-sky-imyLjNyR6Jk", width: 4000, height: 3000, alt: "a large body of water sitting under a blue sky" },
  { id: "K5znWBYPk-Q", slug: "a-beach-with-blue-water", unsplashPhotoId: "photo-1659695089569-1dd183fa5aaa", photographer: "Mari A", photographerUrl: "https://unsplash.com/@marikoa888", photoUrl: "https://unsplash.com/photos/a-beach-with-blue-water-K5znWBYPk-Q", width: 4608, height: 3456, alt: "a beach with blue water" },
  { id: "TWoL-QCZubY", slug: "body-of-water-near-trees-and-mountain-cliff-during-daytime", unsplashPhotoId: "photo-1510414842594-a61c69b5ae57", photographer: "Derek Thomson", photographerUrl: "https://unsplash.com/@derekthomson", photoUrl: "https://unsplash.com/photos/body-of-water-near-trees-and-mountain-cliff-during-daytime-TWoL-QCZubY", width: 5472, height: 3648, alt: "body of water near trees and mountain cliff during daytime" },
  { id: "SD2QJjsktqo", slug: "a-body-of-water-with-a-rock-in-the-middle-of-it", unsplashPhotoId: "photo-1707007694363-b8afb46ed639", photographer: "Phill Brown", photographerUrl: "https://unsplash.com/@phillbrown", photoUrl: "https://unsplash.com/photos/a-body-of-water-with-a-rock-in-the-middle-of-it-SD2QJjsktqo", width: 4934, height: 3289, alt: "a body of water with a rock in the middle of it" },
  { id: "o2pYEwOZSBY", slug: "blue-sea-under-blue-sky", unsplashPhotoId: "photo-1560884694-1113fbe64385", photographer: "Quentin Grignet", photographerUrl: "https://unsplash.com/@qgrignet", photoUrl: "https://unsplash.com/photos/blue-sea-under-blue-sky-o2pYEwOZSBY", width: 5999, height: 3955, alt: "blue sea under blue sky" },
  { id: "TN2Azd9iPaM", slug: "body-of-water-and-mountain-with-fog", unsplashPhotoId: "photo-1505216128104-44f34619861f", photographer: "Patrick Schöpflin", photographerUrl: "https://unsplash.com/@patrickschoepflin", photoUrl: "https://unsplash.com/photos/body-of-water-and-mountain-with-fog-TN2Azd9iPaM", width: 5472, height: 3648, alt: "body of water and mountain with fog" },
  { id: "_e-8w6ZM9ZI", slug: "photo-of-sea-wave-crashing-shore", unsplashPhotoId: "photo-1474180348636-b816e168b85e", photographer: "Colin Maynard", photographerUrl: "https://unsplash.com/@fromnineteen80", photoUrl: "https://unsplash.com/photos/photo-of-sea-wave-crashing-shore-_e-8w6ZM9ZI", width: 2500, height: 1667, alt: "photo of sea wave crashing shore" },
  { id: "cuTk59eNHUE", slug: "aerial-photo-body-of-water", unsplashPhotoId: "photo-1444260239795-df1f0772a252", photographer: "Mathew Waters", photographerUrl: "https://unsplash.com/@mathew_waters", photoUrl: "https://unsplash.com/photos/aerial-photo-body-of-water-cuTk59eNHUE", width: 3456, height: 2304, alt: "aerial photo body of water" },
  { id: "GM_vVlxHgWs", slug: "brown-and-green-mountain-beside-body-of-water-under-blue-sky-du", unsplashPhotoId: "photo-1598094173058-bf20d44c2919", photographer: "Maria Carlos Cardeiro", photographerUrl: "https://unsplash.com/@maria_carlos_cardeiro", photoUrl: "https://unsplash.com/photos/brown-and-green-mountain-beside-body-of-water-under-blue-sky-during-daytime-GM_vVlxHgWs", width: 7667, height: 5133, alt: "brown and green mountain beside body of water under blue sky during daytime" },
  { id: "JiQzHopWhFY", slug: "a-view-of-the-ocean-with-mountains-in-the-background", unsplashPhotoId: "photo-1698658433471-c26ed91802b7", photographer: "Fiona Dodd", photographerUrl: "https://unsplash.com/@funen99", photoUrl: "https://unsplash.com/photos/a-view-of-the-ocean-with-mountains-in-the-background-JiQzHopWhFY", width: 4000, height: 3000, alt: "a view of the ocean with mountains in the background" },
  { id: "Z6LcQP2iZ_Y", slug: "calm-blue-water-meets-rocky-coastline-under-a-vast-sky", unsplashPhotoId: "photo-1778642127979-2cfc7adf55d9", photographer: "Petra Reid", photographerUrl: "https://unsplash.com/@createinme_nz", photoUrl: "https://unsplash.com/photos/calm-blue-water-meets-rocky-coastline-under-a-vast-sky-Z6LcQP2iZ_Y", width: 6720, height: 4480, alt: "Calm blue water meets rocky coastline under a vast sky" },
  { id: "bW2tiamU7js", slug: "waves-crashing-on-rocky-shore-with-blue-ocean", unsplashPhotoId: "photo-1760210099008-6127f1f2b8b2", photographer: "Vincent Y @USA", photographerUrl: "https://unsplash.com/@vincentyuan87", photoUrl: "https://unsplash.com/photos/waves-crashing-on-rocky-shore-with-blue-ocean-bW2tiamU7js", width: 6000, height: 4000, alt: "Waves crashing on rocky shore with blue ocean" },
  { id: "HB2f8zoJyWk", slug: "serene-ocean-at-dusk-with-city-lights-reflecting-on-water", unsplashPhotoId: "photo-1780724856242-7df50c124576", photographer: "Ning H", photographerUrl: "https://unsplash.com/@inscribingpractice", photoUrl: "https://unsplash.com/photos/serene-ocean-at-dusk-with-city-lights-reflecting-on-water-HB2f8zoJyWk", width: 5184, height: 3456, alt: "Serene ocean at dusk with city lights reflecting on water" },
  { id: "t_kEC-OGhj4", slug: "a-body-of-water-surrounded-by-mountains-and-rocks", unsplashPhotoId: "photo-1683041133509-aab050b20b18", photographer: "Sergei Gussev", photographerUrl: "https://unsplash.com/@sergei_gussev", photoUrl: "https://unsplash.com/photos/a-body-of-water-surrounded-by-mountains-and-rocks-t_kEC-OGhj4", width: 4096, height: 2144, alt: "a body of water surrounded by mountains and rocks" },
  { id: "QFVsotOQ4Mg", slug: "black-and-white-ocean-waves-crashing-against-a-rocky-shore", unsplashPhotoId: "photo-1785335872743-1b391da814cb", photographer: "gianna branco", photographerUrl: "https://unsplash.com/@gianna_branco", photoUrl: "https://unsplash.com/photos/black-and-white-ocean-waves-crashing-against-a-rocky-shore-QFVsotOQ4Mg", width: 3637, height: 2374, alt: "Black and white ocean waves crashing against a rocky shore" },
  { id: "YuLkou_nbm4", slug: "ocean-waves-breaking-on-a-rocky-coast-with-sea-stacks", unsplashPhotoId: "photo-1778362700038-6d28cfd0829b", photographer: "E R", photographerUrl: "https://unsplash.com/@100picrats", photoUrl: "https://unsplash.com/photos/ocean-waves-breaking-on-a-rocky-coast-with-sea-stacks-YuLkou_nbm4", width: 6000, height: 4000, alt: "Ocean waves breaking on a rocky coast with sea stacks" },
  { id: "ZikN2efj6wY", slug: "ocean-waves-crash-on-a-rocky-shore-framed-by-trees", unsplashPhotoId: "photo-1782840934163-ca2de856c222", photographer: "Trenton Alarcon", photographerUrl: "https://unsplash.com/@tatertots4robots", photoUrl: "https://unsplash.com/photos/ocean-waves-crash-on-a-rocky-shore-framed-by-trees-ZikN2efj6wY", width: 5898, height: 3932, alt: "Ocean waves crash on a rocky shore framed by trees" },
  { id: "k-uGIyIrbPc", slug: "rocky-coastline-with-blue-ocean-waves-under-a-clear-sky", unsplashPhotoId: "photo-1779685030678-7d84c9e43274", photographer: "Yina Li", photographerUrl: "https://unsplash.com/@jonlykk", photoUrl: "https://unsplash.com/photos/rocky-coastline-with-blue-ocean-waves-under-a-clear-sky-k-uGIyIrbPc", width: 6000, height: 4000, alt: "Rocky coastline with blue ocean waves under a clear sky" },
  { id: "OjhvyK1b1pw", slug: "waves-crash-against-rocky-shore-in-black-and-white", unsplashPhotoId: "photo-1778880434025-fcc1dafd06bd", photographer: "Bernd 📷 Dittrich", photographerUrl: "https://unsplash.com/@hdbernd", photoUrl: "https://unsplash.com/photos/waves-crash-against-rocky-shore-in-black-and-white-OjhvyK1b1pw", width: 4096, height: 2731, alt: "Waves crash against rocky shore in black and white" },
  { id: "5wq565Qn6R4", slug: "crashing-ocean-waves-against-a-rugged-rocky-coastline", unsplashPhotoId: "photo-1782141255963-60cd4a736b37", photographer: "Diwei Zhu", photographerUrl: "https://unsplash.com/@chwdy", photoUrl: "https://unsplash.com/photos/crashing-ocean-waves-against-a-rugged-rocky-coastline-5wq565Qn6R4", width: 5333, height: 4000, alt: "Crashing ocean waves against a rugged, rocky coastline" },
  { id: "nFztBcyuR8k", slug: "waves-crash-against-dark-volcanic-rocks-on-the-coast", unsplashPhotoId: "photo-1760293898552-2f47478ccbae", photographer: "Wolfgang Hasselmann", photographerUrl: "https://unsplash.com/@wolfgang_hasselmann", photoUrl: "https://unsplash.com/photos/waves-crash-against-dark-volcanic-rocks-on-the-coast-nFztBcyuR8k", width: 5584, height: 3723, alt: "Waves crash against dark volcanic rocks on the coast" },
  { id: "8lk-O7byhHQ", slug: "green-coastal-dunes-meet-the-ocean-under-a-clear-sky", unsplashPhotoId: "photo-1762684440458-2806483e67ed", photographer: "Panchanok Juntanarach", photographerUrl: "https://unsplash.com/@mindddd", photoUrl: "https://unsplash.com/photos/green-coastal-dunes-meet-the-ocean-under-a-clear-sky-8lk-O7byhHQ", width: 6000, height: 4000, alt: "Green coastal dunes meet the ocean under a clear sky" },
  { id: "pQHggGFgF8A", slug: "ocean-waves-crash-on-a-sandy-beach-with-distant-hills", unsplashPhotoId: "photo-1774081149544-67027c0fbef9", photographer: "Emma", photographerUrl: "https://unsplash.com/@pictures102", photoUrl: "https://unsplash.com/photos/ocean-waves-crash-on-a-sandy-beach-with-distant-hills-pQHggGFgF8A", width: 6000, height: 4000, alt: "Ocean waves crash on a sandy beach with distant hills" },
  { id: "0eukOYdCfHY", slug: "large-waves-crash-against-dark-rocks-under-a-grey-sky", unsplashPhotoId: "photo-1778846181379-bc907c811d28", photographer: "Wolfgang Hasselmann", photographerUrl: "https://unsplash.com/@wolfgang_hasselmann", photoUrl: "https://unsplash.com/photos/large-waves-crash-against-dark-rocks-under-a-grey-sky-0eukOYdCfHY", width: 7008, height: 4672, alt: "Large waves crash against dark rocks under a grey sky" },
  { id: "lSH3qj6kcfE", slug: "waves-crash-against-red-rocks-on-the-coast", unsplashPhotoId: "photo-1767954579128-223750902477", photographer: "Arnold Zhou", photographerUrl: "https://unsplash.com/@arnold_zhou", photoUrl: "https://unsplash.com/photos/waves-crash-against-red-rocks-on-the-coast-lSH3qj6kcfE", width: 8160, height: 6120, alt: "Waves crash against red rocks on the coast" },
  { id: "Rmo_E6nUpJk", slug: "brown-rock-formation-on-body-of-water-under-blue-sky", unsplashPhotoId: "photo-1596391691172-3359c29c6451", photographer: "Red Zeppelin", photographerUrl: "https://unsplash.com/@redzeppelin", photoUrl: "https://unsplash.com/photos/brown-rock-formation-on-body-of-water-under-blue-sky-Rmo_E6nUpJk", width: 7306, height: 3509, alt: "brown rock formation on body of water under blue sky" },
  { id: "zGto-tO0-_c", slug: "turquoise-waves-crashing-on-a-sandy-shore", unsplashPhotoId: "photo-1763866522069-abe2d1129b3a", photographer: "Fumiaki Hayashi", photographerUrl: "https://unsplash.com/@fumirin", photoUrl: "https://unsplash.com/photos/turquoise-waves-crashing-on-a-sandy-shore-zGto-tO0-_c", width: 6240, height: 4160, alt: "Turquoise waves crashing on a sandy shore" },
  { id: "A1C8UhDGwVQ", slug: "ocean-waves-crash-against-a-rugged-coastline-with-dry-brush", unsplashPhotoId: "photo-1777245398141-ef61c61cc6e7", photographer: "Sam", photographerUrl: "https://unsplash.com/@samtakespictures", photoUrl: "https://unsplash.com/photos/ocean-waves-crash-against-a-rugged-coastline-with-dry-brush-A1C8UhDGwVQ", width: 7008, height: 4672, alt: "Ocean waves crash against a rugged coastline with dry brush" },
  { id: "Ga1lfTDEA0o", slug: "waves-crash-against-rocky-shore-under-a-clear-sky", unsplashPhotoId: "photo-1761502127815-2760f20ab3e0", photographer: "ersma", photographerUrl: "https://unsplash.com/@ersmalat", photoUrl: "https://unsplash.com/photos/waves-crash-against-rocky-shore-under-a-clear-sky-Ga1lfTDEA0o", width: 4592, height: 3448, alt: "Waves crash against rocky shore under a clear sky" },
  { id: "8ogOeJFk9nY", slug: "waves-crash-against-rocky-shore-under-cloudy-sky", unsplashPhotoId: "photo-1773569447781-240f27c62fa5", photographer: "Wolfgang Hasselmann", photographerUrl: "https://unsplash.com/@wolfgang_hasselmann", photoUrl: "https://unsplash.com/photos/waves-crash-against-rocky-shore-under-cloudy-sky-8ogOeJFk9nY", width: 4912, height: 3264, alt: "Waves crash against rocky shore under cloudy sky" },
  { id: "JChxa1ymivE", slug: "rocky-coastline-with-clear-blue-ocean-water", unsplashPhotoId: "photo-1778362930925-09486e3dc4ea", photographer: "E R", photographerUrl: "https://unsplash.com/@100picrats", photoUrl: "https://unsplash.com/photos/rocky-coastline-with-clear-blue-ocean-water-JChxa1ymivE", width: 6000, height: 4000, alt: "Rocky coastline with clear blue ocean water" },
];

export function photoBySlug(slug: string): Photo | undefined {
  return PHOTOS.find((photo) => photo.slug === slug);
}

export function photoStandardSrc(photo: Photo, width = 1920): string {
  return `https://images.unsplash.com/${photo.unsplashPhotoId}?auto=format&fit=crop&w=${width}&q=90`;
}

export function photoStandardSrcset(photo: Photo): string {
  return [1280, 1920, 2560, 3200]
    .map(w => `https://images.unsplash.com/${photo.unsplashPhotoId}?auto=format&fit=crop&w=${w}&q=90 ${w}w`)
    .join(", ");
}

export function photoGainmapSrc(photo: Photo): string {
  return `/photos/${photo.slug}/gainmap.jpg`;
}

export function photoGainmapSrcset(photo: Photo): string {
  return [400, 800, 1280].map(w => `/photos/${photo.slug}/gainmap-${w}.jpg ${w}w`).join(", ");
}

export function withUnsplashReferral(url: string): string {
  const join = url.includes("?") ? "&" : "?";
  return `${url}${join}utm_source=gainmaps&utm_medium=referral`;
}

export function photosPageCount(): number {
  return Math.ceil(PHOTOS.length / PAGE_SIZE);
}

export function photosForPage(page: number): readonly Photo[] {
  const total = photosPageCount();
  const current = Math.min(Math.max(page, 1), Math.max(total, 1));
  const start = (current - 1) * PAGE_SIZE;
  return PHOTOS.slice(start, start + PAGE_SIZE);
}

export function clampPhotoPage(page: number): number {
  const total = photosPageCount();
  if (!Number.isFinite(page) || page < 1) return 1;
  return Math.min(Math.floor(page), Math.max(total, 1));
}
