/**
 * 100 Unsplash photographs for /photos. Standard tiles hotlink the CDN;
 * Ultra tiles are local gain map JPEGs at /photos/{slug}/gainmap.jpg (boost 1.0 max).
 *
 * Rebuild Ultra files: npx tsx tools/photos/build-photos.ts
 */
export type Photo = {
  readonly id: string;
  readonly slug: string;
  /** images.unsplash.com filename, e.g. photo-1506905925346-21bda4d32df4 */
  readonly unsplashPhotoId: string;
  readonly photographer: string;
  readonly photographerUrl: string;
  readonly photoUrl: string;
  readonly width: number;
  readonly height: number;
  readonly alt: string;
};

export const PAGE_SIZE = 12;

export const PHOTOS: readonly Photo[] = [
  { id: "zmA2gYoK844", slug: "green-pine-trees", unsplashPhotoId: "photo-1562605270-3cdc52af7f5d", photographer: "Ethan Dow", photographerUrl: "https://unsplash.com/@ethandow", photoUrl: "https://unsplash.com/photos/green-pine-trees-zmA2gYoK844", width: 1900, height: 3040, alt: "green pine trees" },
  { id: "9bBEDfzbDc4", slug: "a-clear-chunk-of-ice-on-a-dark-pebble-beach-near-the-ocean", unsplashPhotoId: "photo-1787238347746-44391edcfa32", photographer: "Benjamin Chambon", photographerUrl: "https://unsplash.com/@benjamin_photo_lab", photoUrl: "https://unsplash.com/photos/ice-chunk-on-dark-pebble-beach-9bBEDfzbDc4", width: 4000, height: 6000, alt: "A clear chunk of ice on a dark pebble beach near the ocean" },
  { id: "12Dk7KemMnQ", slug: "a-green-and-black-butterfly-sitting-on-a-green-leaf", unsplashPhotoId: "photo-1704230640818-26c444cf487d", photographer: "Emanuel Haas", photographerUrl: "https://unsplash.com/@dermanuskript", photoUrl: "https://unsplash.com/photos/a-green-and-black-butterfly-sitting-on-a-green-leaf-12Dk7KemMnQ", width: 4000, height: 6000, alt: "a green and black butterfly sitting on a green leaf" },
  { id: "qsdkMlbfne4", slug: "a-seal-rests-on-a-shallow-sandbar-in-calm-water", unsplashPhotoId: "photo-1784978516675-8daa424836f5", photographer: "Jeremy Hynes", photographerUrl: "https://unsplash.com/@hynesight", photoUrl: "https://unsplash.com/photos/a-seal-rests-on-a-shallow-sandbar-in-calm-water-qsdkMlbfne4", width: 7660, height: 3830, alt: "A seal rests on a shallow sandbar in calm water" },
  { id: "BOe54W1l_uk", slug: "a-delicate-dried-sprig-with-tiny-buds-against-a-bright-white", unsplashPhotoId: "photo-1787036864627-178da7ec01fd", photographer: "Andrey K", photographerUrl: "https://unsplash.com/@anamnesis33", photoUrl: "https://unsplash.com/photos/dried-sprig-on-white-background-BOe54W1l_uk", width: 4672, height: 7008, alt: "A delicate dried sprig with tiny buds against a bright white background" },
  { id: "RFoBPg0KAGc", slug: "a-close-up-of-an-elephant-s-skin-with-a-green-spot-in-the-ce", unsplashPhotoId: "photo-1694587967979-3ee29d91291a", photographer: "Yifu Wu", photographerUrl: "https://unsplash.com/@nnonno", photoUrl: "https://unsplash.com/photos/a-close-up-of-an-elephants-skin-with-a-green-spot-in-the-center-RFoBPg0KAGc", width: 5464, height: 3640, alt: "a close up of an elephant's skin with a green spot in the center" },
  { id: "0pbZeoE2aio", slug: "a-white-wagtail-perched-on-a-rock", unsplashPhotoId: "photo-1745812741995-1364235a754e", photographer: "Bastian Cimander", photographerUrl: "https://unsplash.com/@buzztea", photoUrl: "https://unsplash.com/photos/a-white-wagtail-perched-on-a-rock-0pbZeoE2aio", width: 5504, height: 4128, alt: "A white wagtail perched on a rock" },
  { id: "91pnJ8G2gzQ", slug: "three-canada-geese-swimming-in-a-line-on-vibrant-turquoise-w", unsplashPhotoId: "photo-1786524216518-82876d57f319", photographer: "Tom Macret", photographerUrl: "https://unsplash.com/@tom_macret", photoUrl: "https://unsplash.com/photos/canada-geese-on-turquoise-water-91pnJ8G2gzQ", width: 3825, height: 5737, alt: "Three Canada geese swimming in a line on vibrant turquoise water" },
  { id: "-PvICnpWGlc", slug: "two-people-on-a-rocky-cliff-overlooking-a-valley-under-a-low", unsplashPhotoId: "photo-1787055923390-67a2dbac36b0", photographer: "Michael Shtern", photographerUrl: "https://unsplash.com/@mic222", photoUrl: "https://unsplash.com/photos/people-on-rocky-cliff-at-valley--PvICnpWGlc", width: 6720, height: 3780, alt: "Two people on a rocky cliff overlooking a valley under a low sun" },
  { id: "1_tJ8v3ORxE", slug: "a-blackbird-perched-on-a-branch-with-berries", unsplashPhotoId: "photo-1768339932948-dc7b77b24e32", photographer: "Bastian Cimander", photographerUrl: "https://unsplash.com/@buzztea", photoUrl: "https://unsplash.com/photos/a-blackbird-perched-on-a-branch-with-berries-1_tJ8v3ORxE", width: 4856, height: 3642, alt: "A blackbird perched on a branch with berries" },
  { id: "-zrRKebyM8c", slug: "turquoise-river-flows-through-a-dramatic-rocky-canyon", unsplashPhotoId: "photo-1785131455100-7f15d21ebffe", photographer: "Mahyar Yeganeh", photographerUrl: "https://unsplash.com/@nvamahyar", photoUrl: "https://unsplash.com/photos/turquoise-river-flows-through-a-dramatic-rocky-canyon--zrRKebyM8c", width: 3024, height: 4032, alt: "Turquoise river flows through a dramatic, rocky canyon" },
  { id: "fmTtt98qKKM", slug: "a-dhole-stands-in-a-dense-forest", unsplashPhotoId: "photo-1782965140692-6ee6329f1523", photographer: "Rakesh Arora", photographerUrl: "https://unsplash.com/@rapssafaris", photoUrl: "https://unsplash.com/photos/a-dhole-stands-in-a-dense-forest-fmTtt98qKKM", width: 3003, height: 1999, alt: "A dhole stands in a dense forest" },
  { id: "I8uRAuI5JF4", slug: "a-black-dog-on-a-rock-with-colorful-mountains", unsplashPhotoId: "photo-1778701985068-4561674b45d8", photographer: "Ahmed", photographerUrl: "https://unsplash.com/@mutecevvil", photoUrl: "https://unsplash.com/photos/a-black-dog-on-a-rock-with-colorful-mountains-I8uRAuI5JF4", width: 4583, height: 6874, alt: "A black dog on a rock with colorful mountains" },
  { id: "l3Pvd4M3Css", slug: "low-sun-with-lens-flare-over-a-forested-valley-and-granite-c", unsplashPhotoId: "photo-1787170426598-858e57c774dd", photographer: "Priyank Pathak", photographerUrl: "https://unsplash.com/@ppriyank", photoUrl: "https://unsplash.com/photos/low-sun-over-yosemite-valley-cliffs-l3Pvd4M3Css", width: 9459, height: 5475, alt: "Low sun with lens flare over a forested valley and granite cliffs in Yosemite" },
  { id: "maKSDW4Ucoc", slug: "a-person-walks-along-a-desert-sand-dune-at-sunset", unsplashPhotoId: "photo-1781902834540-4604713b7e1b", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/a-person-walks-along-a-desert-sand-dune-at-sunset-maKSDW4Ucoc", width: 3525, height: 5287, alt: "A person walks along a desert sand dune at sunset" },
  { id: "ygRIDv3W6Ec", slug: "zebras-in-a-golden-sunlit-grassy-field", unsplashPhotoId: "photo-1781730655215-63a2a92623e4", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/zebras-in-a-golden-sunlit-grassy-field-ygRIDv3W6Ec", width: 5713, height: 3809, alt: "Zebras in a golden, sunlit grassy field" },
  { id: "qsQNjjHjFns", slug: "striking-layered-desert-mountain-under-a-beautiful-sunset-sk", unsplashPhotoId: "photo-1785142893888-58e3954672db", photographer: "Kilic-Emre Akdag", photographerUrl: "https://unsplash.com/@kilicemre7007", photoUrl: "https://unsplash.com/photos/striking-layered-desert-mountain-under-a-beautiful-sunset-sky-qsQNjjHjFns", width: 4024, height: 3018, alt: "Striking layered desert mountain under a beautiful sunset sky" },
  { id: "i_J0c5m6yvc", slug: "a-person-in-a-red-cloak-on-a-vast-sand-dune-at-golden-hour", unsplashPhotoId: "photo-1786300412449-875316124ba1", photographer: "Rafael Peier", photographerUrl: "https://unsplash.com/@rafaelpeier", photoUrl: "https://unsplash.com/photos/person-in-red-cloak-on-sand-dune-i_J0c5m6yvc", width: 4382, height: 6573, alt: "A person in a red cloak on a vast sand dune at golden hour" },
  { id: "j0M14wYc1_A", slug: "wooden-cabin-in-a-lush-green-meadow-before-a-mountain", unsplashPhotoId: "photo-1784019226271-f89c21f7791a", photographer: "Yousef Salhamoud", photographerUrl: "https://unsplash.com/@salhamoud", photoUrl: "https://unsplash.com/photos/wooden-cabin-in-a-lush-green-meadow-before-a-mountain-j0M14wYc1_A", width: 4470, height: 6705, alt: "Wooden cabin in a lush green meadow before a mountain" },
  { id: "s2F_H5M7-Vs", slug: "yellow-house-with-wooden-shutters-and-mountain-in-background", unsplashPhotoId: "photo-1785739125961-0c316bc80d13", photographer: "Arjun Raj", photographerUrl: "https://unsplash.com/@mr_hell", photoUrl: "https://unsplash.com/photos/yellow-house-with-wooden-shutters-and-mountain-in-background-s2F_H5M7-Vs", width: 5949, height: 3347, alt: "Yellow house with wooden shutters and mountain in background" },
  { id: "INEhddM6mTI", slug: "a-concrete-courtyard-with-wooden-doors-and-a-stone-sculpture", unsplashPhotoId: "photo-1787228461026-b11d75a448aa", photographer: "Mattia Revelant", photographerUrl: "https://unsplash.com/@vez02", photoUrl: "https://unsplash.com/photos/concrete-courtyard-with-stone-sculpture-INEhddM6mTI", width: 4160, height: 6240, alt: "A concrete courtyard with wooden doors and a stone sculpture beneath mountain peaks" },
  { id: "ttMdFEwlayw", slug: "a-person-looking-out-over-a-lake-and-mountains-from-a-metal", unsplashPhotoId: "photo-1786813478692-b6df54dc3f6c", photographer: "Dawid Tkocz", photographerUrl: "https://unsplash.com/@dawidtkocz", photoUrl: "https://unsplash.com/photos/person-overlooking-lake-and-mountains-ttMdFEwlayw", width: 3840, height: 2560, alt: "A person looking out over a lake and mountains from a metal railing" },
  { id: "gHAbh2kG15c", slug: "a-person-in-a-red-jacket-photographing-a-sign-for-san-vito-d", unsplashPhotoId: "photo-1787223921392-cdd9255147fd", photographer: "Mattia Revelant", photographerUrl: "https://unsplash.com/@vez02", photoUrl: "https://unsplash.com/photos/san-vito-di-cadore-sign-in-mountains-gHAbh2kG15c", width: 4160, height: 6240, alt: "A person in a red jacket photographing a sign for San Vito di Cadore" },
  { id: "Yh3alvVRvRA", slug: "people-on-a-grassy-hillside-with-a-wooden-mountain-hut-below", unsplashPhotoId: "photo-1787224641466-9195e22b85b7", photographer: "Mattia Revelant", photographerUrl: "https://unsplash.com/@vez02", photoUrl: "https://unsplash.com/photos/people-on-grassy-mountain-hillside-Yh3alvVRvRA", width: 6240, height: 4160, alt: "People on a grassy hillside with a wooden mountain hut below rocky peaks" },
  { id: "F7mbMhINkHY", slug: "two-red-plastic-chairs-at-a-table-with-an-orange-cloth-befor", unsplashPhotoId: "photo-1786299599950-4845576af365", photographer: "Alexander Kaufmann", photographerUrl: "https://unsplash.com/@alexander_kaufmann", photoUrl: "https://unsplash.com/photos/red-chairs-and-table-at-green-gate-F7mbMhINkHY", width: 4672, height: 7008, alt: "Two red plastic chairs at a table with an orange cloth before a green gate" },
  { id: "F0DONqMyJks", slug: "monk-in-orange-robes-raises-hands-towards-temple-building", unsplashPhotoId: "photo-1785334012218-a43bcee64525", photographer: "Paul Macdonald", photographerUrl: "https://unsplash.com/@paulmacdonald", photoUrl: "https://unsplash.com/photos/monk-in-orange-robes-raises-hands-towards-temple-building-F0DONqMyJks", width: 5482, height: 3647, alt: "Monk in orange robes raises hands towards temple building" },
  { id: "odQRH_qjQPY", slug: "a-delivery-scooter-on-a-city-street-with-blurred-traffic-in", unsplashPhotoId: "photo-1786801769556-a9db4b49905d", photographer: "Sohan Rayguru", photographerUrl: "https://unsplash.com/@sohan_r", photoUrl: "https://unsplash.com/photos/delivery-scooter-on-busy-city-street-odQRH_qjQPY", width: 2963, height: 4444, alt: "A delivery scooter on a city street with blurred traffic in motion" },
  { id: "Hrr800ZW9T4", slug: "a-statue-of-a-person-with-a-hat-on-his-head", unsplashPhotoId: "photo-1736823750021-92b3cea76e6a", photographer: "Saksham Vikram", photographerUrl: "https://unsplash.com/@26svk", photoUrl: "https://unsplash.com/photos/a-statue-of-a-person-with-a-hat-on-his-head-Hrr800ZW9T4", width: 4000, height: 6016, alt: "A statue of a person with a hat on his head" },
  { id: "Gt_ZeRJ7ETo", slug: "a-beautiful-coastline-with-mountains-and-boats", unsplashPhotoId: "photo-1754532432708-4bf134683082", photographer: "Gatot Adri", photographerUrl: "https://unsplash.com/@garakta", photoUrl: "https://unsplash.com/photos/a-beautiful-coastline-with-mountains-and-boats-Gt_ZeRJ7ETo", width: 2688, height: 4032, alt: "A beautiful coastline with mountains and boats" },
  { id: "kv0pMXztQzs", slug: "people-in-traditional-balinese-attire-carrying-ceremonial-fi", unsplashPhotoId: "photo-1773555899937-229935a87166", photographer: "Eyestetix Studio", photographerUrl: "https://unsplash.com/@eyestetix_studio", photoUrl: "https://unsplash.com/photos/people-in-traditional-balinese-attire-carrying-ceremonial-figures-kv0pMXztQzs", width: 3264, height: 4896, alt: "People in traditional balinese attire carrying ceremonial figures" },
  { id: "hDsMuIpWSJE", slug: "a-person-walks-rainy-street-at-night-holding-an-umbrella", unsplashPhotoId: "photo-1782835615101-267ac940e7ac", photographer: "Julien", photographerUrl: "https://unsplash.com/@domsson", photoUrl: "https://unsplash.com/photos/a-person-walks-rainy-street-at-night-holding-an-umbrella-hDsMuIpWSJE", width: 3840, height: 2400, alt: "A person walks rainy street at night holding an umbrella" },
  { id: "lOmsiNYE_o0", slug: "a-city-street-filled-with-lots-of-tall-buildings", unsplashPhotoId: "photo-1731658218464-51d8c83b55cb", photographer: "Jie Yeu Teoh", photographerUrl: "https://unsplash.com/@jieyeu", photoUrl: "https://unsplash.com/photos/a-city-street-filled-with-lots-of-tall-buildings-lOmsiNYE_o0", width: 2234, height: 3351, alt: "A city street filled with lots of tall buildings" },
  { id: "6MVBinSgPJQ", slug: "the-ornate-tiled-roof-of-the-temple-of-heaven-in-beijing-fra", unsplashPhotoId: "photo-1786957116293-8bb0d585ce87", photographer: "Nora", photographerUrl: "https://unsplash.com/@tibuww", photoUrl: "https://unsplash.com/photos/temple-of-heaven-roof-in-beijing-6MVBinSgPJQ", width: 4016, height: 6016, alt: "The ornate tiled roof of the Temple of Heaven in Beijing framed by trees" },
  { id: "PR0BJetIWZY", slug: "red-wooden-pillars-with-gold-cloud-patterns-in-a-traditional", unsplashPhotoId: "photo-1786158284793-838baa0f78fe", photographer: "Ahmet Yüksek ✪", photographerUrl: "https://unsplash.com/@ahmetyuksek", photoUrl: "https://unsplash.com/photos/red-wooden-pillars-with-gold-patterns-PR0BJetIWZY", width: 5248, height: 7868, alt: "Red wooden pillars with gold cloud patterns in a traditional temple structure" },
  { id: "W3VNMAcfkf4", slug: "a-round-building-with-a-balcony-on-top-of-a-hill", unsplashPhotoId: "photo-1701688174684-26593150720a", photographer: "Artur Adilkhanian", photographerUrl: "https://unsplash.com/@br00m", photoUrl: "https://unsplash.com/photos/a-round-building-with-a-balcony-on-top-of-a-hill-W3VNMAcfkf4", width: 4075, height: 6112, alt: "a round building with a balcony on top of a hill" },
  { id: "hzFB8dt7vkY", slug: "angular-red-building-architecture-under-blue-sky", unsplashPhotoId: "photo-1785741392701-e96608b3555f", photographer: "Declan Sun", photographerUrl: "https://unsplash.com/@declansun", photoUrl: "https://unsplash.com/photos/angular-red-building-architecture-under-blue-sky-hzFB8dt7vkY", width: 5184, height: 3632, alt: "Angular red building architecture under blue sky" },
  { id: "dRYFOlN8V_I", slug: "modern-building-s-concrete-pillars-and-spherical-joint-again", unsplashPhotoId: "photo-1781155966422-f9da74fe3931", photographer: "Declan Sun", photographerUrl: "https://unsplash.com/@declansun", photoUrl: "https://unsplash.com/photos/modern-buildings-concrete-pillars-and-spherical-joint-against-blue-sky-dRYFOlN8V_I", width: 6336, height: 9504, alt: "Modern building's concrete pillars and spherical joint against blue sky" },
  { id: "1Jcs15r_DRI", slug: "a-round-orange-table-with-chairs-on-a-balcony-with-potted-pl", unsplashPhotoId: "photo-1786816442802-f44b4a1be3aa", photographer: "Federico Garaffi", photographerUrl: "https://unsplash.com/@fedingo13_photography", photoUrl: "https://unsplash.com/photos/orange-table-and-chairs-on-balcony-1Jcs15r_DRI", width: 4020, height: 6024, alt: "A round orange table with chairs on a balcony with potted plants" },
  { id: "v1CC-_TSjbA", slug: "a-cylindrical-tower-with-tiled-walls-illuminated-by-a-glowin", unsplashPhotoId: "photo-1787239179212-34efa6984e43", photographer: "Shahabudin Ibragimov", photographerUrl: "https://unsplash.com/@sb_dn", photoUrl: "https://unsplash.com/photos/cylindrical-tower-with-glowing-light-v1CC-_TSjbA", width: 7878, height: 5252, alt: "A cylindrical tower with tiled walls illuminated by a glowing circular light fixture" },
  { id: "aZNHr-mJF8o", slug: "a-modern-skyscraper-facade-with-grid-patterns-of-square-wind", unsplashPhotoId: "photo-1787001251232-4506703ff24c", photographer: "Pawel Czerwinski", photographerUrl: "https://unsplash.com/@pawel_czerwinski", photoUrl: "https://unsplash.com/photos/skyscraper-facade-with-grid-windows-aZNHr-mJF8o", width: 3354, height: 5031, alt: "A modern skyscraper facade with grid patterns of square windows and grey panels" },
  { id: "OfiRomq1-kg", slug: "a-modern-geometric-house-with-a-grass-roof-in-a-grassy-lands", unsplashPhotoId: "photo-1787052022279-8cdef22fad49", photographer: "Georgi Kalaydzhiev", photographerUrl: "https://unsplash.com/@jorok", photoUrl: "https://unsplash.com/photos/geometric-house-with-grass-roof-OfiRomq1-kg", width: 4136, height: 6106, alt: "A modern geometric house with a grass roof in a grassy landscape" },
  { id: "z5OPX4iahJ0", slug: "an-aerial-view-of-a-building-with-a-complex-red-tiled-roof", unsplashPhotoId: "photo-1786486307773-072da9c9a6f5", photographer: "Remigiusz Dettlaff", photographerUrl: "https://unsplash.com/@photodesignremigiuszdettlaff", photoUrl: "https://unsplash.com/photos/building-with-complex-red-tiled-roof-z5OPX4iahJ0", width: 5780, height: 5780, alt: "An aerial view of a building with a complex red tiled roof" },
  { id: "B7n4l4sJ2O0", slug: "a-large-statue-of-a-man-pushing-a-wall", unsplashPhotoId: "photo-1776136736025-f5867048cf73", photographer: "krzhck", photographerUrl: "https://unsplash.com/@krzhck", photoUrl: "https://unsplash.com/photos/a-large-statue-of-a-man-pushing-a-wall-B7n4l4sJ2O0", width: 6607, height: 4405, alt: "A large statue of a man pushing a wall" },
  { id: "yj8Ok-PMFQQ", slug: "the-vaulted-ceiling-of-st-mary-s-church-in-derby-with-blue-p", unsplashPhotoId: "photo-1787063944174-132442e42bd5", photographer: "Mike Hindle", photographerUrl: "https://unsplash.com/@mikehindle", photoUrl: "https://unsplash.com/photos/vaulted-ceiling-of-st-marys-church-yj8Ok-PMFQQ", width: 5954, height: 7939, alt: "The vaulted ceiling of St Mary's Church in Derby with blue panels and arches" },
  { id: "xDV6YuFBkAo", slug: "shadow-and-sunlight-cast-upon-a-concrete-staircase", unsplashPhotoId: "photo-1743760676341-ac13322116ad", photographer: "Aleksandr Zaitsev", photographerUrl: "https://unsplash.com/@anwaltzzz", photoUrl: "https://unsplash.com/photos/shadow-and-sunlight-cast-upon-a-concrete-staircase-xDV6YuFBkAo", width: 4554, height: 8096, alt: "Shadow and sunlight cast upon a concrete staircase" },
  { id: "ImKtzwJRBN0", slug: "historic-white-church-building-on-a-sandy-dune-landscape", unsplashPhotoId: "photo-1780656093756-0faf1a88159f", photographer: "Max Böhme", photographerUrl: "https://unsplash.com/@max_boehme", photoUrl: "https://unsplash.com/photos/historic-white-church-building-on-a-sandy-dune-landscape-ImKtzwJRBN0", width: 4495, height: 6743, alt: "Historic white church building on a sandy dune landscape" },
  { id: "C41Fj7LPMK0", slug: "a-large-building-with-a-curved-roof-next-to-a-tall-building", unsplashPhotoId: "photo-1724178472101-85b2f9668d16", photographer: "Aliaksei Lepik", photographerUrl: "https://unsplash.com/@vegfrt", photoUrl: "https://unsplash.com/photos/a-large-building-with-a-curved-roof-next-to-a-tall-building-C41Fj7LPMK0", width: 4160, height: 6240, alt: "A large building with a curved roof next to a tall building" },
  { id: "ZLrR_Shlab0", slug: "modern-building-with-unique-angular-architecture-and-stone-f", unsplashPhotoId: "photo-1771608017074-e13e8136ec88", photographer: "Sara Ruffoni", photographerUrl: "https://unsplash.com/@ssarasframes", photoUrl: "https://unsplash.com/photos/modern-building-with-unique-angular-architecture-and-stone-facade-ZLrR_Shlab0", width: 2846, height: 3558, alt: "Modern building with unique angular architecture and stone facade" },
  { id: "emk5uwNbP6Q", slug: "exterior-concrete-spiral-staircase-on-a-brick-building", unsplashPhotoId: "photo-1783588848164-fc90d0e63951", photographer: "Sijmen van Hooff", photographerUrl: "https://unsplash.com/@sijmen89", photoUrl: "https://unsplash.com/photos/exterior-concrete-spiral-staircase-on-a-brick-building-emk5uwNbP6Q", width: 5666, height: 8513, alt: "Exterior concrete spiral staircase on a brick building" },
  { id: "AjKly-ZTuEY", slug: "geometric-concrete-stairs-cast-shadows-in-sunlight", unsplashPhotoId: "photo-1774762720340-8067294bb494", photographer: "Palina Kharlanovich", photographerUrl: "https://unsplash.com/@polinamorf", photoUrl: "https://unsplash.com/photos/geometric-concrete-stairs-cast-shadows-in-sunlight-AjKly-ZTuEY", width: 4160, height: 6240, alt: "Geometric concrete stairs cast shadows in sunlight" },
  { id: "OtlFbnn8_64", slug: "graffiti-on-a-concrete-bridge-support-with-a-long-shadow-cas", unsplashPhotoId: "photo-1787090607181-5cae7b643e53", photographer: "Çağan Kılıç", photographerUrl: "https://unsplash.com/@caganklc", photoUrl: "https://unsplash.com/photos/graffiti-on-concrete-bridge-support-OtlFbnn8_64", width: 4000, height: 6000, alt: "Graffiti on a concrete bridge support with a long shadow cast across the ground" },
  { id: "jxQ3UhI4nHc", slug: "pigeon-perched-on-a-rooftop-with-a-bridge-at-sunset", unsplashPhotoId: "photo-1784350723088-e2860c208c7d", photographer: "Nguyễn Đức", photographerUrl: "https://unsplash.com/@nguyenducsjk", photoUrl: "https://unsplash.com/photos/pigeon-perched-on-a-rooftop-with-a-bridge-at-sunset-jxQ3UhI4nHc", width: 3680, height: 2944, alt: "Pigeon perched on a rooftop with a bridge at sunset" },
  { id: "k6AjF4a3htU", slug: "a-carpet-laying-on-the-floor-next-to-a-door", unsplashPhotoId: "photo-1677928709896-696774cefc02", photographer: "Burçin Ergünt", photographerUrl: "https://unsplash.com/@burcinergunt", photoUrl: "https://unsplash.com/photos/a-carpet-laying-on-the-floor-next-to-a-door-k6AjF4a3htU", width: 5152, height: 7728, alt: "a carpet laying on the floor next to a door" },
  { id: "7kecBDSUkJE", slug: "people-preparing-colorful-inflatable-rafts-on-a-concrete-riv", unsplashPhotoId: "photo-1786354791804-33fb0b927e8e", photographer: "Hayden Chen", photographerUrl: "https://unsplash.com/@hayden0325", photoUrl: "https://unsplash.com/photos/people-preparing-colorful-rafting-boats-7kecBDSUkJE", width: 4000, height: 3000, alt: "People preparing colorful inflatable rafts on a concrete riverbank for a rafting trip" },
  { id: "1EKbg6P84lQ", slug: "a-dog-laying-on-the-ground-next-to-a-pair-of-shoes", unsplashPhotoId: "photo-1677928708120-5695c5f43785", photographer: "Burçin Ergünt", photographerUrl: "https://unsplash.com/@burcinergunt", photoUrl: "https://unsplash.com/photos/a-dog-laying-on-the-ground-next-to-a-pair-of-shoes-1EKbg6P84lQ", width: 5152, height: 7728, alt: "a dog laying on the ground next to a pair of shoes" },
  { id: "wMFlUbLa1Is", slug: "person-carrying-a-large-bundle-walks-up-sunlit-yellow-stairs", unsplashPhotoId: "photo-1784350723640-f45922c903fd", photographer: "Nguyễn Đức", photographerUrl: "https://unsplash.com/@nguyenducsjk", photoUrl: "https://unsplash.com/photos/person-carrying-a-large-bundle-walks-up-sunlit-yellow-stairs-wMFlUbLa1Is", width: 3437, height: 4296, alt: "Person carrying a large bundle walks up sunlit yellow stairs" },
  { id: "HHh8Na_gHpY", slug: "outdoor-seating-area-with-amusement-park-background", unsplashPhotoId: "photo-1778855181135-052dd7cd1a99", photographer: "N1CE", photographerUrl: "https://unsplash.com/@n1ce", photoUrl: "https://unsplash.com/photos/outdoor-seating-area-with-amusement-park-background-HHh8Na_gHpY", width: 3923, height: 5884, alt: "Outdoor seating area with amusement park background" },
  { id: "9jV6ekrRcw8", slug: "a-man-walks-past-a-pink-building-in-strong-sunlight", unsplashPhotoId: "photo-1783004964068-7c2a62a5456e", photographer: "Liam Scotchmer", photographerUrl: "https://unsplash.com/@liam_scotchmer", photoUrl: "https://unsplash.com/photos/a-man-walks-past-a-pink-building-in-strong-sunlight-9jV6ekrRcw8", width: 2704, height: 3380, alt: "A man walks past a pink building in strong sunlight" },
  { id: "gyMTdP9K8Wo", slug: "a-person-walking-down-a-sidewalk-under-a-bridge", unsplashPhotoId: "photo-1672477671521-296d9957e091", photographer: "Julian", photographerUrl: "https://unsplash.com/@julian21", photoUrl: "https://unsplash.com/photos/a-person-walking-down-a-sidewalk-under-a-bridge-gyMTdP9K8Wo", width: 6000, height: 4000, alt: "a person walking down a sidewalk under a bridge" },
  { id: "rr8bSU2PPog", slug: "people-looking-out-from-a-ferry-window-at-a-city-waterfront", unsplashPhotoId: "photo-1787226958395-fd12537d061a", photographer: "Tolga Ahmetler", photographerUrl: "https://unsplash.com/@t_ahmetler", photoUrl: "https://unsplash.com/photos/people-on-ferry-at-city-waterfront-rr8bSU2PPog", width: 7911, height: 5274, alt: "People looking out from a ferry window at a city waterfront with graffiti" },
  { id: "6h64lsp2muc", slug: "an-izakaya-with-a-wooden-facade-and-a-red-paper-lantern-in-t", unsplashPhotoId: "photo-1787187230145-30dcb1cb30ff", photographer: "jack berry", photographerUrl: "https://unsplash.com/@jackseeberry", photoUrl: "https://unsplash.com/photos/izakaya-with-wooden-facade-in-taito-city-6h64lsp2muc", width: 5152, height: 7728, alt: "An izakaya with a wooden facade and a red paper lantern in Taito City" },
  { id: "PY1DGkSC-ZY", slug: "three-wheeled-vehicles-drive-down-a-european-street", unsplashPhotoId: "photo-1757359415247-f0022d529332", photographer: "Richard Stachmann", photographerUrl: "https://unsplash.com/@stachmann", photoUrl: "https://unsplash.com/photos/three-wheeled-vehicles-drive-down-a-european-street-PY1DGkSC-ZY", width: 2207, height: 3130, alt: "Three-wheeled vehicles drive down a european street" },
  { id: "G7cowNRODpc", slug: "graffiti-art-poses-a-question-to-the-viewer", unsplashPhotoId: "photo-1747893540663-3cf46cf04668", photographer: "Claudio Schwarz", photographerUrl: "https://unsplash.com/@purzlbaum", photoUrl: "https://unsplash.com/photos/graffiti-art-poses-a-question-to-the-viewer-G7cowNRODpc", width: 5503, height: 3669, alt: "Graffiti art poses a question to the viewer" },
  { id: "NpdSnQMXh4I", slug: "bright-blue-van-parked-against-a-modern-apartment-building", unsplashPhotoId: "photo-1780686616131-36eb579dd43b", photographer: "Marcus Lenk", photographerUrl: "https://unsplash.com/@marcuslenk", photoUrl: "https://unsplash.com/photos/bright-blue-van-parked-against-a-modern-apartment-building-NpdSnQMXh4I", width: 2467, height: 3700, alt: "Bright blue van parked against a modern apartment building" },
  { id: "BwOmcGEXaCU", slug: "a-yellow-car-parked-on-the-side-of-the-road", unsplashPhotoId: "photo-1694661986807-90f3e4905480", photographer: "Firas Wardhana", photographerUrl: "https://unsplash.com/@firassu", photoUrl: "https://unsplash.com/photos/a-yellow-car-parked-on-the-side-of-the-road-BwOmcGEXaCU", width: 4608, height: 3072, alt: "a yellow car parked on the side of the road" },
  { id: "kApQdoePawQ", slug: "two-people-sitting-on-a-blue-bridge-railing-pointing-toward", unsplashPhotoId: "photo-1787226964789-7ae90f47fea8", photographer: "Tolga Ahmetler", photographerUrl: "https://unsplash.com/@t_ahmetler", photoUrl: "https://unsplash.com/photos/people-on-blue-bridge-railing-kApQdoePawQ", width: 8215, height: 5477, alt: "Two people sitting on a blue bridge railing pointing toward dark water below" },
  { id: "CTYLYkOQPEw", slug: "a-man-with-a-beard-wearing-a-patterned-headscarf-and-turquoi", unsplashPhotoId: "photo-1786536567828-29783fa33341", photographer: "AmirHadi Manavi Moghadam", photographerUrl: "https://unsplash.com/@amirhadimanavimoghadam", photoUrl: "https://unsplash.com/photos/man-with-beard-and-turquoise-beads-CTYLYkOQPEw", width: 6336, height: 9504, alt: "A man with a beard wearing a patterned headscarf and turquoise beads holding a glass" },
  { id: "tDBXrGDJNs4", slug: "vietnamese-woman-in-ao-dai-and-non-la-standing-outdoors", unsplashPhotoId: "photo-1780645240967-25e9db74e8a5", photographer: "Bin Thieu", photographerUrl: "https://unsplash.com/@binthieu", photoUrl: "https://unsplash.com/photos/vietnamese-woman-in-ao-dai-and-non-la-standing-outdoors-tDBXrGDJNs4", width: 8256, height: 5504, alt: "Vietnamese woman in ao dai and non la standing outdoors" },
  { id: "3ZkcVGfVNQA", slug: "woman-holding-a-red-book-in-a-field-at-sunset", unsplashPhotoId: "photo-1785593414189-2e591e4ca6df", photographer: "Ciocan Ciprian", photographerUrl: "https://unsplash.com/@cipriann", photoUrl: "https://unsplash.com/photos/woman-holding-a-red-book-in-a-field-at-sunset-3ZkcVGfVNQA", width: 3253, height: 4554, alt: "Woman holding a red book in a field at sunset" },
  { id: "oubQZW1Fe1g", slug: "a-person-in-mad-hatter-costume-with-elaborate-makeup", unsplashPhotoId: "photo-1783712279783-10a07163075f", photographer: "Royce Fonseca", photographerUrl: "https://unsplash.com/@casunshine0508", photoUrl: "https://unsplash.com/photos/a-person-in-mad-hatter-costume-with-elaborate-makeup-oubQZW1Fe1g", width: 5464, height: 8192, alt: "A person in mad hatter costume with elaborate makeup" },
  { id: "TCsu5aGuK5Y", slug: "a-man-and-a-woman-with-foreheads-touching-in-a-soft-focus-ou", unsplashPhotoId: "photo-1786335203787-2abf4a0d7778", photographer: "Brooke Balentine", photographerUrl: "https://unsplash.com/@brookebalentine", photoUrl: "https://unsplash.com/photos/man-and-woman-with-foreheads-touching-TCsu5aGuK5Y", width: 5464, height: 8192, alt: "A man and a woman with foreheads touching in a soft-focus outdoor setting" },
  { id: "dzMc7xHIgcY", slug: "a-woman-with-curly-hair-and-pink-makeup-holding-her-hands-to", unsplashPhotoId: "photo-1787197790662-039081f257e1", photographer: "🔥John Rodriguez🔥", photographerUrl: "https://unsplash.com/@firephotos", photoUrl: "https://unsplash.com/photos/woman-with-curly-hair-and-makeup-dzMc7xHIgcY", width: 5224, height: 7629, alt: "A woman with curly hair and pink makeup holding her hands together" },
  { id: "mfnRy1iEVUM", slug: "woman-in-red-dress-with-raised-arms-on-rocky-coast", unsplashPhotoId: "photo-1783916810161-e5abe0a3f649", photographer: "sammy swae", photographerUrl: "https://unsplash.com/@sammyswae", photoUrl: "https://unsplash.com/photos/woman-in-red-dress-with-raised-arms-on-rocky-coast-mfnRy1iEVUM", width: 3072, height: 4608, alt: "Woman in red dress with raised arms on rocky coast" },
  { id: "-igL7OWINS0", slug: "two-women-in-white-crop-tops-standing-back-to-back-against-a", unsplashPhotoId: "photo-1787057856849-fb849d01f9ad", photographer: "David Banjo", photographerUrl: "https://unsplash.com/@davidbvnjo", photoUrl: "https://unsplash.com/photos/two-women-back-to-back--igL7OWINS0", width: 2672, height: 4000, alt: "Two women in white crop tops standing back to back against a concrete wall" },
  { id: "maJCVS9Xm1I", slug: "a-person-in-a-grey-fleece-hoodie-playing-a-vintage-arcade-ga", unsplashPhotoId: "photo-1786989906324-d2ab05f95f27", photographer: "Kade Tyack", photographerUrl: "https://unsplash.com/@kade_tyack", photoUrl: "https://unsplash.com/photos/person-playing-vintage-arcade-game-maJCVS9Xm1I", width: 3116, height: 3895, alt: "A person in a grey fleece hoodie playing a vintage arcade game" },
  { id: "Yh88Ag5d98M", slug: "silhouettes-of-people-against-a-bright-low-sun-in-a-clear-sk", unsplashPhotoId: "photo-1786962730761-cf13c9b7c360", photographer: "Oleksii Tsaryuk", photographerUrl: "https://unsplash.com/@photobyredder", photoUrl: "https://unsplash.com/photos/people-silhouettes-against-low-sun-Yh88Ag5d98M", width: 6000, height: 4000, alt: "Silhouettes of people against a bright low sun in a clear sky" },
  { id: "3bk6bfnTNvE", slug: "arm-with-a-minimalist-tattoo-and-vibrant-red-nail-polish", unsplashPhotoId: "photo-1783916813244-fe2db3dba422", photographer: "sammy swae", photographerUrl: "https://unsplash.com/@sammyswae", photoUrl: "https://unsplash.com/photos/arm-with-a-minimalist-tattoo-and-vibrant-red-nail-polish-3bk6bfnTNvE", width: 4672, height: 7008, alt: "Arm with a minimalist tattoo and vibrant red nail polish" },
  { id: "zX0ggWsVyMM", slug: "man-fishing-on-a-bridge-with-galata-tower-in-background", unsplashPhotoId: "photo-1782823388692-2ca64e395879", photographer: "Tolga Ahmetler", photographerUrl: "https://unsplash.com/@t_ahmetler", photoUrl: "https://unsplash.com/photos/man-fishing-on-a-bridge-with-galata-tower-in-background-zX0ggWsVyMM", width: 5073, height: 7610, alt: "Man fishing on a bridge with galata tower in background" },
  { id: "kARpL0jw9Ak", slug: "a-white-egg-on-a-feather", unsplashPhotoId: "photo-1660385381636-fc743a8c091d", photographer: "Alex Shuper", photographerUrl: "https://unsplash.com/@alexshuperart", photoUrl: "https://unsplash.com/photos/a-white-egg-on-a-feather-kARpL0jw9Ak", width: 4500, height: 6000, alt: "a white egg on a feather" },
  { id: "EJhtDSR-ghc", slug: "a-close-up-of-a-white-and-blue-object", unsplashPhotoId: "photo-1716643406202-f3a5f212f827", photographer: "Noam Cohen", photographerUrl: "https://unsplash.com/@semineural", photoUrl: "https://unsplash.com/photos/a-close-up-of-a-white-and-blue-object-EJhtDSR-ghc", width: 2700, height: 3375, alt: "a close up of a white and blue object" },
  { id: "07pe6lFRZU8", slug: "a-pair-of-blue-double-doors-with-unique-gold-car-shaped-door", unsplashPhotoId: "photo-1787001251418-d83f436978c8", photographer: "Pawel Czerwinski", photographerUrl: "https://unsplash.com/@pawel_czerwinski", photoUrl: "https://unsplash.com/photos/blue-doors-with-gold-car-handles-07pe6lFRZU8", width: 3781, height: 5671, alt: "A pair of blue double doors with unique gold car-shaped door handles" },
  { id: "BpRgAsy0JTo", slug: "an-open-window-floats-above-clouds-with-a-flowing-path", unsplashPhotoId: "photo-1779243829348-85bf26cff23b", photographer: "Mehrab Sium", photographerUrl: "https://unsplash.com/@mehrab_sium", photoUrl: "https://unsplash.com/photos/an-open-window-floats-above-clouds-with-a-flowing-path-BpRgAsy0JTo", width: 3888, height: 5832, alt: "An open window floats above clouds with a flowing path" },
  { id: "oU-qoEjNnHM", slug: "a-blue-and-white-swirl-on-a-gray-background", unsplashPhotoId: "photo-1689141047490-a0916682dcfd", photographer: "Milad Fakurian", photographerUrl: "https://unsplash.com/@fakurian", photoUrl: "https://unsplash.com/photos/a-blue-and-white-swirl-on-a-gray-background-oU-qoEjNnHM", width: 4000, height: 2250, alt: "a blue and white swirl on a gray background" },
  { id: "c8JRfw-Cvkg", slug: "brown-concrete-building-during-daytime", unsplashPhotoId: "photo-1581425678921-640bd6314e36", photographer: "olivia calypso", photographerUrl: "https://unsplash.com/@oliviacalypso", photoUrl: "https://unsplash.com/photos/brown-concrete-building-during-daytime-c8JRfw-Cvkg", width: 4000, height: 6000, alt: "brown concrete building during daytime" },
  { id: "CpVwilODVaI", slug: "a-turquoise-volcanic-crater-lake-surrounded-by-rocky-cliffs", unsplashPhotoId: "photo-1786288042250-1258f5839eaf", photographer: "Rowan Heuvel", photographerUrl: "https://unsplash.com/@insolitus", photoUrl: "https://unsplash.com/photos/turquoise-volcanic-crater-lake-CpVwilODVaI", width: 8192, height: 5464, alt: "A turquoise volcanic crater lake surrounded by rocky cliffs under a soft pink sky" },
  { id: "dt5l2bRScfE", slug: "green-bench-against-pink-wall-hazy-city-skyline", unsplashPhotoId: "photo-1779373771064-1c8a6b169c90", photographer: "Anais Chagankerian", photographerUrl: "https://unsplash.com/@anaischagankerian", photoUrl: "https://unsplash.com/photos/green-bench-against-pink-wall-hazy-city-skyline-dt5l2bRScfE", width: 3648, height: 4864, alt: "Green bench against pink wall, hazy city skyline" },
  { id: "lAirgGYIZCo", slug: "abstract-pastel-colors-with-gentle-motion-blur", unsplashPhotoId: "photo-1785678519932-3c606fc366f4", photographer: "Danielle Suijkerbuijk", photographerUrl: "https://unsplash.com/@vandaantje", photoUrl: "https://unsplash.com/photos/abstract-pastel-colors-with-gentle-motion-blur-lAirgGYIZCo", width: 6000, height: 4000, alt: "Abstract pastel colors with gentle motion blur" },
  { id: "f8FgfDNLg2A", slug: "full-moon-in-a-clear-blue-sky-above-buildings", unsplashPhotoId: "photo-1773587040541-6d43f9ae5595", photographer: "Jones Lee", photographerUrl: "https://unsplash.com/@art0819leo", photoUrl: "https://unsplash.com/photos/full-moon-in-a-clear-blue-sky-above-buildings-f8FgfDNLg2A", width: 6000, height: 4500, alt: "Full moon in a clear blue sky above buildings" },
  { id: "T-eW0K_8U6U", slug: "orange-butterfly-with-black-spots-rests-on-a-yellow-flower", unsplashPhotoId: "photo-1784820404977-77c5b4ed0373", photographer: "Bob Brewer", photographerUrl: "https://unsplash.com/@brewbottle", photoUrl: "https://unsplash.com/photos/orange-butterfly-with-black-spots-rests-on-a-yellow-flower-T-eW0K_8U6U", width: 3745, height: 4425, alt: "Orange butterfly with black spots rests on a yellow flower" },
  { id: "PDq5z13syC4", slug: "two-pelicans-resting-with-their-heads-tucked-into-their-feat", unsplashPhotoId: "photo-1783112126399-d9aef8dd21a3", photographer: "Tim Offermans", photographerUrl: "https://unsplash.com/@offermanstim", photoUrl: "https://unsplash.com/photos/two-pelicans-resting-with-their-heads-tucked-into-their-feathers-PDq5z13syC4", width: 4923, height: 3282, alt: "Two pelicans resting with their heads tucked into their feathers" },
  { id: "HTjU2lwGhKI", slug: "several-brown-and-white-jellyfish-swim-against-a-dark-backgr", unsplashPhotoId: "photo-1783112004707-8e12fb897f0c", photographer: "Tim Offermans", photographerUrl: "https://unsplash.com/@offermanstim", photoUrl: "https://unsplash.com/photos/several-brown-and-white-jellyfish-swim-against-a-dark-background-HTjU2lwGhKI", width: 4128, height: 6192, alt: "Several brown and white jellyfish swim against a dark background" },
  { id: "t_MpSogkIBE", slug: "a-small-owl-perched-on-a-tree-branch", unsplashPhotoId: "photo-1769257793784-659a5296e7a5", photographer: "Bob Brewer", photographerUrl: "https://unsplash.com/@brewbottle", photoUrl: "https://unsplash.com/photos/a-small-owl-perched-on-a-tree-branch-t_MpSogkIBE", width: 4399, height: 2966, alt: "A small owl perched on a tree branch" },
  { id: "nVxsqVi3hrk", slug: "a-solitary-egret-stands-in-misty-morning-light-by-reeds", unsplashPhotoId: "photo-1769257423963-36ed2d94d45b", photographer: "Bob Brewer", photographerUrl: "https://unsplash.com/@brewbottle", photoUrl: "https://unsplash.com/photos/a-solitary-egret-stands-in-misty-morning-light-by-reeds-nVxsqVi3hrk", width: 5281, height: 3213, alt: "A solitary egret stands in misty morning light by reeds" },
  { id: "xqyXmQ2Jm8E", slug: "a-young-deer-with-antlers-peeking-from-tall-green-grass", unsplashPhotoId: "photo-1767002866817-f7ce0f0d2e28", photographer: "Wolfgang Hasselmann", photographerUrl: "https://unsplash.com/@wolfgang_hasselmann", photoUrl: "https://unsplash.com/photos/a-young-deer-with-antlers-peeking-from-tall-green-grass-xqyXmQ2Jm8E", width: 6825, height: 4550, alt: "A young deer with antlers peeking from tall green grass" },
  { id: "MFyd7vVCKrs", slug: "a-single-roach-fish-swims-in-dark-water", unsplashPhotoId: "photo-1765464949998-93773ccb6cbf", photographer: "Wolfgang Hasselmann", photographerUrl: "https://unsplash.com/@wolfgang_hasselmann", photoUrl: "https://unsplash.com/photos/a-single-roach-fish-swims-in-dark-water-MFyd7vVCKrs", width: 7008, height: 4672, alt: "A single roach fish swims in dark water" },
  { id: "H8tjd6QjhjY", slug: "a-flock-of-ducks-flying-in-a-clear-blue-sky", unsplashPhotoId: "photo-1764778905931-e5798cf8c42a", photographer: "Bob Brewer", photographerUrl: "https://unsplash.com/@brewbottle", photoUrl: "https://unsplash.com/photos/a-flock-of-ducks-flying-in-a-clear-blue-sky-H8tjd6QjhjY", width: 5336, height: 3406, alt: "A flock of ducks flying in a clear blue sky" },
  { id: "ByOUplbd6Qc", slug: "altar-and-pews-inside-a-dimly-lit-church", unsplashPhotoId: "photo-1761592929435-2006ad6f0df2", photographer: "Christian Harb", photographerUrl: "https://unsplash.com/@c7arb", photoUrl: "https://unsplash.com/photos/altar-and-pews-inside-a-dimly-lit-church-ByOUplbd6Qc", width: 4160, height: 6240, alt: "Altar and pews inside a dimly lit church" },
  { id: "bML3iZqn3nc", slug: "man-s-hands-holding-prayer-beads-raised-in-supplication", unsplashPhotoId: "photo-1762013728442-c6cdde57371e", photographer: "Christian Harb", photographerUrl: "https://unsplash.com/@c7arb", photoUrl: "https://unsplash.com/photos/mans-hands-holding-prayer-beads-raised-in-supplication-bML3iZqn3nc", width: 6240, height: 4457, alt: "Man's hands holding prayer beads, raised in supplication" },
  { id: "SJTO3-MTpBA", slug: "a-silhouette-stands-before-a-cloudy-sunset", unsplashPhotoId: "photo-1752978951972-a8f8d578046e", photographer: "Atul Pandey", photographerUrl: "https://unsplash.com/@iatulp", photoUrl: "https://unsplash.com/photos/a-silhouette-stands-before-a-cloudy-sunset-SJTO3-MTpBA", width: 2469, height: 3292, alt: "A silhouette stands before a cloudy sunset" },
  { id: "7lWyEQCn0qk", slug: "a-person-standing-in-front-of-a-christmas-tree", unsplashPhotoId: "photo-1736123407467-559f4ae6e72b", photographer: "Jahanzeb Ahsan", photographerUrl: "https://unsplash.com/@jahan_photobox", photoUrl: "https://unsplash.com/photos/a-person-standing-in-front-of-a-christmas-tree-7lWyEQCn0qk", width: 4640, height: 3029, alt: "A person standing in front of a christmas tree" },
];

export function photoBySlug(slug: string): Photo | undefined {
  return PHOTOS.find((photo) => photo.slug === slug);
}

export function photoStandardSrc(photo: Photo, width = 1920): string {
  return `https://images.unsplash.com/${photo.unsplashPhotoId}?auto=format&fit=crop&w=${width}&q=90`;
}

export function photoStandardSrcset(photo: Photo): string {
  return [1280, 1920, 2560, 3200]
    .map(w => `https://images.unsplash.com/${photo.unsplashPhotoId}?auto=format&fit=crop&w=${w}&q=90 ${w}w`)
    .join(", ");
}

export function photoGainmapSrc(photo: Photo): string {
  return `/photos/${photo.slug}/gainmap.jpg`;
}

export function withUnsplashReferral(url: string): string {
  const join = url.includes("?") ? "&" : "?";
  return `${url}${join}utm_source=gainmaps&utm_medium=referral`;
}

export function photosPageCount(): number {
  return Math.ceil(PHOTOS.length / PAGE_SIZE);
}

export function photosForPage(page: number): readonly Photo[] {
  const total = photosPageCount();
  const current = Math.min(Math.max(page, 1), Math.max(total, 1));
  const start = (current - 1) * PAGE_SIZE;
  return PHOTOS.slice(start, start + PAGE_SIZE);
}

export function clampPhotoPage(page: number): number {
  const total = photosPageCount();
  if (!Number.isFinite(page) || page < 1) return 1;
  return Math.min(Math.floor(page), Math.max(total, 1));
}
