/**
 * One-shot: read standard-1280.jpg for every catalog slug and emit
 * apps/web/lib/photos/intrinsic-by-slug.ts
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { PHOTOS } from "../../apps/web/lib/photos/catalog.ts";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../../apps/web/public/photos");
const outPath = join(here, "../../apps/web/lib/photos/intrinsic-by-slug.ts");

async function main(): Promise<void> {
  const entries: string[] = [];
  for (const photo of PHOTOS) {
    const meta = await sharp(join(root, photo.slug, "standard-1280.jpg")).metadata();
    if (!meta.width || !meta.height) {
      throw new Error(`missing dimensions for ${photo.slug}`);
    }
    entries.push(`  "${photo.slug}": { width: ${meta.width}, height: ${meta.height} }`);
  }

  const body = `/**
 * Intrinsic pixel size of each shipped standard-1280.jpg / gainmap-1280.jpg pair.
 * Generated by reading the files under public/photos — not catalog originals.
 */
export const PHOTO_INTRINSIC_BY_SLUG: Readonly<
  Record<string, { readonly width: number; readonly height: number }>
> = {
${entries.join(",\n")},
};
`;
  writeFileSync(outPath, body);
  console.log(`wrote ${entries.length} entries -> ${outPath}`);
}

main();
