import { PHOTOS } from "@/lib/photos/catalog";

export type MarkdownPage = "/" | "/developers" | "/docs" | "/photos" | "/logos" | "/about" | "/contact" | "/privacy";
export const MARKDOWN_PATHS = new Set<string>(["/", "/developers", "/docs", "/photos", "/logos", "/about", "/contact", "/privacy"]);

function fm(title: string, description: string, canonical: string, lastUpdated: string): string {
  return `---\ntitle: ${title}\ndescription: ${description}\ncanonical: https://www.gainmaps.com${canonical}\nlast-updated: ${lastUpdated}\n---\n\n`;
}

const CONTENT: Record<string, string> = {
  "/": fm("Gainmaps", "Convert photos to HDR gain map images locally in the browser.", "/", "2026-09-14") + `# Gainmaps\n\nGainmaps converts photos to HDR gain map images locally in the browser. No upload, no server — processing runs in a service worker. Drop any JPEG, PNG, HEIC, WebP, or AVIF into the converter at [/convert](/convert).\n\nThe \`gainmap\` CLI batch-encodes from your terminal. Install via npm (\`npm install -g gainmap\`), Homebrew (\`brew install kirkstrobeck/tap/gainmap\`), or curl (\`curl -fsSL https://gainmaps.com/install.sh | sh\`).\n\nA gain map image encodes an SDR photo plus a brightness map. On HDR displays highlights render above SDR reference white. On SDR displays the image renders normally.\n\nSee the [browser converter](/convert), [photo gallery](/photos), and [developer docs](/developers).`,
  "/developers": fm("Developers · Gainmaps", "CLI, agent skills, and TypeScript library for HDR gain map encoding.", "/developers", "2026-09-14") + `# Developers\n\nGainmaps ships a CLI for batch encoding, an agent skill for Ultra HDR text effects, and a TypeScript library for programmatic encoding. All three are open source.\n\nInstall the CLI: \`npm install -g gainmap\`, \`brew install kirkstrobeck/tap/gainmap\`, or \`curl -fsSL https://gainmaps.com/install.sh | sh\`.\n\nThe full API surface is documented in the OpenAPI 3.1 spec at [/openapi.json](/openapi.json). Every operation has a unique operationId and typed parameters.\n\nFor full reference see [/developers](/developers).`,
  "/docs": fm("Docs · Gainmaps", "What gain map images are, how the browser converter works, and how to use the CLI.", "/docs", "2026-09-14") + `# Docs\n\nA gain map image encodes an SDR base plus a secondary brightness map. On HDR displays the brightness map is applied and highlights render above SDR reference white. On SDR displays only the base is shown — the format is fully backward compatible.\n\nThe browser converter at [/convert](/convert) runs entirely locally. No file leaves your device. Drag and drop any JPEG, PNG, HEIC, WebP, or AVIF.`,
  "/photos": fm("Photos · Gainmaps", `${PHOTOS.length} Unsplash photographs as HDR gain map images.`, "/photos", "2026-09-14") + `# Photos\n\nThe photo gallery at [/photos](/photos) shows ${PHOTOS.length} landscape photographs encoded as gain map images. Each tile shows the SDR base alongside the HDR gain map version. On HDR displays the gain map version renders above SDR reference white.`,
  "/logos": fm("Logos · Gainmaps", "Brand logos encoded as gain map images.", "/logos", "2026-09-14") + `# Logos\n\nThe logo gallery at [/logos](/logos) shows brand logos encoded as gain map images. Each entry links to the SVG original and the gain map JPEG.`,
  "/about": fm("About · Gainmaps", "About the Gainmaps HDR gain map image converter.", "/about", "2026-09-14") + `# About\n\nA gain map image encodes an SDR photo plus a secondary brightness map. On HDR displays (Apple XDR, Android Ultra HDR, Windows Advanced Color) highlights render above SDR reference white. On SDR displays the image renders normally — the format is fully backward compatible.\n\nGainmaps.com demonstrates browser-based conversion. Processing runs locally in a service worker. No file leaves your device, no upload, no server.\n\nThe \`gainmap\` CLI batch-encodes images from your terminal. Install via npm, Homebrew, or curl. It targets ISO 21496-1 (Ultra HDR JPEG).\n\nThe project is open source at [https://github.com/kirkstrobeck/gainmaps](https://github.com/kirkstrobeck/gainmaps).`,
  "/contact": fm("Contact · Gainmaps", "Contact Gainmaps for bugs, feature requests, or security reports.", "/contact", "2026-09-14") + `# Contact\n\nFor bugs, feature requests, and questions, open an issue on GitHub:\n[https://github.com/kirkstrobeck/gainmaps/issues](https://github.com/kirkstrobeck/gainmaps/issues)\n\nFor direct enquiries, email [kirk@strobeck.com](mailto:kirk@strobeck.com).\n\nInclude the input format, operating system, browser or CLI version, and the exact command or conversion step that failed. For rendering questions, say whether HDR is enabled and whether another compatible viewer behaves differently. These details make reports reproducible and separate encoder issues from display capability or application support.\n\nSecurity reports that contain private files or exploit details should use email instead of a public issue. Gainmaps does not provide account support or retain uploaded images because browser conversions stay on the device. Installation and API documentation are available at [/developers](/developers).`,
  "/privacy": fm("Privacy · Gainmaps", "Gainmaps privacy policy: cookies, analytics, and image processing.", "/privacy", "2026-09-14") + `# Privacy\n\n## Cookies\n\n- **last-photo**: Stores the slug of the last hero photo shown on the homepage. Purpose: avoid repeating the same photo on reload. Max-Age: 31536000 (1 year). Not shared with third parties.\n- **site-mode**: Stores your light/dark theme preference. Session-like.\n- **site-ultra**: Stores your Ultra HDR preference. Session-like.\n- **site-intensity**: Stores your Ultra intensity setting. Session-like.\n\n## Analytics\n\nPostHog analytics is proxied via \`/ingest/*\` on this domain. No personally identifiable information is collected or sold.\n\n## Image processing\n\nImages selected in the converter are decoded and encoded on your device. The site does not upload image bytes to Gainmaps servers, create a cloud copy, or associate a conversion with an account. Closing or reloading the page clears the working data held by the browser for that conversion. Downloaded results are saved only where your browser places them.`,
};

export function markdownForPath(path: string): string | null {
  return CONTENT[path] ?? null;
}
