/**
 * Generated by tools/logos/build-logos.ts — do not edit by hand.
 *
 * The most recognizable global brands, in Interbrand Best Global Brands 2025
 * order, that have a premium full-color brand SVG. Every entry has both files
 * on disk under apps/web/public.
 */
export type Company = {
  readonly rank: number;
  /** Stock ticker, when the brand is itself a listed company. */
  readonly ticker?: string;
  readonly name: string;
  readonly slug: string;
  readonly svgPath: string;
  readonly gainmapPath: string;
};

export const COMPANIES: readonly Company[] = [
  { rank: 1, name: "Apple", slug: "apple", svgPath: "/logos/apple/logo.svg", gainmapPath: "/logos/apple/logo-gainmap.jpg" },
  { rank: 2, name: "Microsoft", slug: "microsoft", svgPath: "/logos/microsoft/logo.svg", gainmapPath: "/logos/microsoft/logo-gainmap.jpg" },
  { rank: 4, name: "Google", slug: "google", svgPath: "/logos/google/logo.svg", gainmapPath: "/logos/google/logo-gainmap.jpg" },
  { rank: 6, name: "Toyota", slug: "toyota", svgPath: "/logos/toyota/logo.svg", gainmapPath: "/logos/toyota/logo-gainmap.jpg" },
  { rank: 9, name: "McDonald's", slug: "mcdonalds", svgPath: "/logos/mcdonalds/logo.svg", gainmapPath: "/logos/mcdonalds/logo-gainmap.jpg" },
  { rank: 12, name: "Nike", slug: "nike", svgPath: "/logos/nike/logo.svg", gainmapPath: "/logos/nike/logo-gainmap.jpg" },
  { rank: 13, name: "YouTube", slug: "youtube", svgPath: "/logos/youtube/logo.svg", gainmapPath: "/logos/youtube/logo-gainmap.jpg" },
  { rank: 15, name: "NVIDIA", slug: "nvidia", svgPath: "/logos/nvidia/logo.svg", gainmapPath: "/logos/nvidia/logo-gainmap.jpg" },
  { rank: 18, name: "SAP", slug: "sap", svgPath: "/logos/sap/logo.svg", gainmapPath: "/logos/sap/logo-gainmap.jpg" },
  { rank: 19, name: "Facebook", slug: "facebook", svgPath: "/logos/facebook/logo.svg", gainmapPath: "/logos/facebook/logo-gainmap.jpg" },
  { rank: 25, name: "Spotify", slug: "spotify", svgPath: "/logos/spotify/logo.svg", gainmapPath: "/logos/spotify/logo-gainmap.jpg" },
  { rank: 26, name: "IKEA", slug: "ikea", svgPath: "/logos/ikea/logo.svg", gainmapPath: "/logos/ikea/logo-gainmap.jpg" },
  { rank: 28, name: "ALDI", slug: "aldi", svgPath: "/logos/aldi/logo.svg", gainmapPath: "/logos/aldi/logo-gainmap.jpg" },
  { rank: 29, name: "LinkedIn", slug: "linkedin", svgPath: "/logos/linkedin/logo.svg", gainmapPath: "/logos/linkedin/logo-gainmap.jpg" },
  { rank: 34, name: "Mastercard", slug: "mastercard", svgPath: "/logos/mastercard/logo.svg", gainmapPath: "/logos/mastercard/logo-gainmap.jpg" },
  { rank: 36, name: "Kia", slug: "kia", svgPath: "/logos/kia/logo.svg", gainmapPath: "/logos/kia/logo-gainmap.jpg" },
  { rank: 38, name: "Pepsi", slug: "pepsi", svgPath: "/logos/pepsi/logo.svg", gainmapPath: "/logos/pepsi/logo-gainmap.jpg" },
  { rank: 39, name: "Netflix", slug: "netflix", svgPath: "/logos/netflix/logo.svg", gainmapPath: "/logos/netflix/logo-gainmap.jpg" },
  { rank: 45, name: "Gillette", slug: "gillette", svgPath: "/logos/gillette/logo.svg", gainmapPath: "/logos/gillette/logo-gainmap.jpg" },
  { rank: 51, name: "Adidas", slug: "adidas", svgPath: "/logos/adidas/logo.svg", gainmapPath: "/logos/adidas/logo-gainmap.jpg" },
  { rank: 53, name: "Nintendo", slug: "nintendo", svgPath: "/logos/nintendo/logo.svg", gainmapPath: "/logos/nintendo/logo-gainmap.jpg" },
  { rank: 56, name: "PayPal", slug: "paypal", svgPath: "/logos/paypal/logo.svg", gainmapPath: "/logos/paypal/logo-gainmap.jpg" },
  { rank: 58, name: "Zoom", slug: "zoom", svgPath: "/logos/zoom/logo.svg", gainmapPath: "/logos/zoom/logo-gainmap.jpg" },
  { rank: 67, name: "HP", slug: "hp", svgPath: "/logos/hp/logo.svg", gainmapPath: "/logos/hp/logo-gainmap.jpg" },
  { rank: 69, name: "Puma", slug: "puma", svgPath: "/logos/puma/logo.svg", gainmapPath: "/logos/puma/logo-gainmap.jpg" },
  { rank: 72, name: "HSBC", slug: "hsbc", svgPath: "/logos/hsbc/logo.svg", gainmapPath: "/logos/hsbc/logo-gainmap.jpg" },
  { rank: 73, name: "3M", slug: "3m", svgPath: "/logos/3m/logo.svg", gainmapPath: "/logos/3m/logo-gainmap.jpg" },
  { rank: 79, name: "Jeep", slug: "jeep", svgPath: "/logos/jeep/logo.svg", gainmapPath: "/logos/jeep/logo-gainmap.jpg" },
  { rank: 81, name: "Xiaomi", slug: "xiaomi", svgPath: "/logos/xiaomi/logo.svg", gainmapPath: "/logos/xiaomi/logo-gainmap.jpg" },
  { rank: 88, name: "DHL", slug: "dhl", svgPath: "/logos/dhl/logo.svg", gainmapPath: "/logos/dhl/logo-gainmap.jpg" },
  { rank: 90, name: "Harley-Davidson", slug: "harley-davidson", svgPath: "/logos/harley-davidson/logo.svg", gainmapPath: "/logos/harley-davidson/logo-gainmap.jpg" },
  { rank: 94, name: "Adobe", slug: "adobe", svgPath: "/logos/adobe/logo.svg", gainmapPath: "/logos/adobe/logo-gainmap.jpg" },
  { rank: 96, name: "H&M", slug: "h-and-m", svgPath: "/logos/h-and-m/logo.svg", gainmapPath: "/logos/h-and-m/logo-gainmap.jpg" },
  { rank: 100, name: "UPS", slug: "ups", svgPath: "/logos/ups/logo.svg", gainmapPath: "/logos/ups/logo-gainmap.jpg" },
  { rank: 102, name: "Starbucks", slug: "starbucks", svgPath: "/logos/starbucks/logo.svg", gainmapPath: "/logos/starbucks/logo-gainmap.jpg" },
];

export function companyBySlug(slug: string): Company | undefined {
  return COMPANIES.find((company) => company.slug === slug);
}

export const LOGO_SRC_WIDTHS = [128, 256, 512, 768, 1024] as const;

export function logoGainmapSrcset(company: Company): string {
  return LOGO_SRC_WIDTHS.map(w => `/logos/${company.slug}/logo-gainmap-${w}.jpg ${w}w`).join(", ");
}
