/**
 * Generated by tools/logos/build-logos.ts — do not edit by hand.
 *
 * The most recognizable global brands, in Interbrand Best Global Brands 2025
 * order, that have a premium full-color brand SVG. Every entry has both files
 * on disk under apps/web/public.
 */
export type Company = {
  readonly rank: number;
  /** Stock ticker, when the brand is itself a listed company. */
  readonly ticker?: string;
  readonly name: string;
  readonly slug: string;
  readonly svgPath: string;
  readonly gainmapPath: string;
};

export const COMPANIES: readonly Company[] = [
  { rank: 2, name: "Microsoft", slug: "microsoft", svgPath: "/logos/microsoft/logo.svg", gainmapPath: "/logos/microsoft/logo-gainmap.jpg" },
  { rank: 3, name: "Amazon", slug: "amazon", svgPath: "/logos/amazon/logo.svg", gainmapPath: "/logos/amazon/logo-gainmap.jpg" },
  { rank: 4, name: "Google", slug: "google", svgPath: "/logos/google/logo.svg", gainmapPath: "/logos/google/logo-gainmap.jpg" },
  { rank: 6, name: "Toyota", slug: "toyota", svgPath: "/logos/toyota/logo.svg", gainmapPath: "/logos/toyota/logo-gainmap.jpg" },
  { rank: 8, name: "Instagram", slug: "instagram", svgPath: "/logos/instagram/logo.svg", gainmapPath: "/logos/instagram/logo-gainmap.jpg" },
  { rank: 9, name: "McDonald's", slug: "mcdonalds", svgPath: "/logos/mcdonalds/logo.svg", gainmapPath: "/logos/mcdonalds/logo-gainmap.jpg" },
  { rank: 14, name: "BMW", slug: "bmw", svgPath: "/logos/bmw/logo.svg", gainmapPath: "/logos/bmw/logo-gainmap.jpg" },
  { rank: 15, name: "NVIDIA", slug: "nvidia", svgPath: "/logos/nvidia/logo.svg", gainmapPath: "/logos/nvidia/logo-gainmap.jpg" },
  { rank: 18, name: "SAP", slug: "sap", svgPath: "/logos/sap/logo.svg", gainmapPath: "/logos/sap/logo-gainmap.jpg" },
  { rank: 20, name: "Adobe", slug: "adobe", svgPath: "/logos/adobe/logo.svg", gainmapPath: "/logos/adobe/logo-gainmap.jpg" },
  { rank: 28, name: "Netflix", slug: "netflix", svgPath: "/logos/netflix/logo.svg", gainmapPath: "/logos/netflix/logo-gainmap.jpg" },
  { rank: 29, name: "Honda", slug: "honda", svgPath: "/logos/honda/logo.svg", gainmapPath: "/logos/honda/logo-gainmap.jpg" },
  { rank: 32, name: "Booking.com", slug: "booking-com", svgPath: "/logos/booking-com/logo.svg", gainmapPath: "/logos/booking-com/logo-gainmap.jpg" },
  { rank: 35, name: "IKEA", slug: "ikea", svgPath: "/logos/ikea/logo.svg", gainmapPath: "/logos/ikea/logo-gainmap.jpg" },
  { rank: 36, name: "Mastercard", slug: "mastercard", svgPath: "/logos/mastercard/logo.svg", gainmapPath: "/logos/mastercard/logo-gainmap.jpg" },
  { rank: 37, name: "Accenture", slug: "accenture", svgPath: "/logos/accenture/logo.svg", gainmapPath: "/logos/accenture/logo-gainmap.jpg" },
  { rank: 38, name: "Pepsi", slug: "pepsi", svgPath: "/logos/pepsi/logo.svg", gainmapPath: "/logos/pepsi/logo-gainmap.jpg" },
  { rank: 39, name: "Qualcomm", slug: "qualcomm", svgPath: "/logos/qualcomm/logo.svg", gainmapPath: "/logos/qualcomm/logo-gainmap.jpg" },
  { rank: 40, name: "PayPal", slug: "paypal", svgPath: "/logos/paypal/logo.svg", gainmapPath: "/logos/paypal/logo-gainmap.jpg" },
  { rank: 43, name: "AXA", slug: "axa", svgPath: "/logos/axa/logo.svg", gainmapPath: "/logos/axa/logo-gainmap.jpg" },
  { rank: 46, name: "UPS", slug: "ups", svgPath: "/logos/ups/logo.svg", gainmapPath: "/logos/ups/logo-gainmap.jpg" },
  { rank: 47, name: "UNIQLO", slug: "uniqlo", svgPath: "/logos/uniqlo/logo.svg", gainmapPath: "/logos/uniqlo/logo-gainmap.jpg" },
  { rank: 50, name: "LEGO", slug: "lego", svgPath: "/logos/lego/logo.svg", gainmapPath: "/logos/lego/logo-gainmap.jpg" },
  { rank: 53, name: "Nintendo", slug: "nintendo", svgPath: "/logos/nintendo/logo.svg", gainmapPath: "/logos/nintendo/logo-gainmap.jpg" },
  { rank: 58, name: "Spotify", slug: "spotify", svgPath: "/logos/spotify/logo.svg", gainmapPath: "/logos/spotify/logo-gainmap.jpg" },
  { rank: 60, name: "Pampers", slug: "pampers", svgPath: "/logos/pampers/logo.svg", gainmapPath: "/logos/pampers/logo-gainmap.jpg" },
  { rank: 61, name: "eBay", slug: "ebay", svgPath: "/logos/ebay/logo.svg", gainmapPath: "/logos/ebay/logo-gainmap.jpg" },
  { rank: 62, name: "Citi", slug: "citi", svgPath: "/logos/citi/logo.svg", gainmapPath: "/logos/citi/logo-gainmap.jpg" },
  { rank: 63, name: "Nescafé", slug: "nescafe", svgPath: "/logos/nescafe/logo.svg", gainmapPath: "/logos/nescafe/logo-gainmap.jpg" },
  { rank: 66, name: "Budweiser", slug: "budweiser", svgPath: "/logos/budweiser/logo.svg", gainmapPath: "/logos/budweiser/logo-gainmap.jpg" },
  { rank: 68, name: "H&M", slug: "h-and-m", svgPath: "/logos/h-and-m/logo.svg", gainmapPath: "/logos/h-and-m/logo-gainmap.jpg" },
  { rank: 71, name: "Intel", slug: "intel", svgPath: "/logos/intel/logo.svg", gainmapPath: "/logos/intel/logo-gainmap.jpg" },
  { rank: 72, name: "HSBC", slug: "hsbc", svgPath: "/logos/hsbc/logo.svg", gainmapPath: "/logos/hsbc/logo-gainmap.jpg" },
  { rank: 74, name: "Philips", slug: "philips", svgPath: "/logos/philips/logo.svg", gainmapPath: "/logos/philips/logo-gainmap.jpg" },
  { rank: 75, name: "LinkedIn", slug: "linkedin", svgPath: "/logos/linkedin/logo.svg", gainmapPath: "/logos/linkedin/logo-gainmap.jpg" },
  { rank: 76, name: "Colgate", slug: "colgate", svgPath: "/logos/colgate/logo.svg", gainmapPath: "/logos/colgate/logo-gainmap.jpg" },
  { rank: 77, name: "Santander", slug: "santander", svgPath: "/logos/santander/logo.svg", gainmapPath: "/logos/santander/logo-gainmap.jpg" },
  { rank: 84, name: "Caterpillar", slug: "caterpillar", svgPath: "/logos/caterpillar/logo.svg", gainmapPath: "/logos/caterpillar/logo-gainmap.jpg" },
  { rank: 85, name: "Nasdaq", slug: "nasdaq", svgPath: "/logos/nasdaq/logo.svg", gainmapPath: "/logos/nasdaq/logo-gainmap.jpg" },
  { rank: 90, name: "BYD", slug: "byd", svgPath: "/logos/byd/logo.svg", gainmapPath: "/logos/byd/logo-gainmap.jpg" },
  { rank: 91, name: "Danone", slug: "danone", svgPath: "/logos/danone/logo.svg", gainmapPath: "/logos/danone/logo-gainmap.jpg" },
  { rank: 92, name: "FedEx", slug: "fedex", svgPath: "/logos/fedex/logo.svg", gainmapPath: "/logos/fedex/logo-gainmap.jpg" },
  { rank: 99, name: "Shopify", slug: "shopify", svgPath: "/logos/shopify/logo.svg", gainmapPath: "/logos/shopify/logo-gainmap.jpg" },
  { rank: 100, name: "DHL", slug: "dhl", svgPath: "/logos/dhl/logo.svg", gainmapPath: "/logos/dhl/logo-gainmap.jpg" },
  { rank: 101, name: "American Express", slug: "american-express", svgPath: "/logos/american-express/logo.svg", gainmapPath: "/logos/american-express/logo-gainmap.jpg" },
];

export function companyBySlug(slug: string): Company | undefined {
  return COMPANIES.find((company) => company.slug === slug);
}

export function logoGainmapSrcset(company: Company): string {
  return [128, 256, 512, 1024].map(w => `/logos/${company.slug}/logo-gainmap-${w}.jpg ${w}w`).join(", ");
}
