// Gainmaps by Kirk Strobeck – https://gainmaps.com

/** Renders apps/web/lib/logos/companies.ts from a resolved seed list. */
import type { LogoSeed } from "./sources.ts";

export function renderCompaniesModule(seeds: readonly LogoSeed[]): string {
  const rows = seeds
    .map((seed) => {
      const fields = [
        `rank: ${seed.rank}`,
        // Optional: most of these brands are product or private brands with no
        // ticker of their own. Omitted entirely rather than written as "".
        ...(seed.ticker ? [`ticker: ${quote(seed.ticker)}`] : []),
        `name: ${quote(seed.name)}`,
        `slug: ${quote(seed.slug)}`,
        `svgPath: ${quote(`/logos/${seed.slug}/logo.svg`)}`,
        `gainmapPath: ${quote(`/logos/${seed.slug}/logo-gainmap.jpg`)}`,
      ];
      return `  { ${fields.join(", ")} },`;
    })
    .join("\n");

  return `/**
 * Generated by tools/logos/build-logos.ts — do not edit by hand.
 *
 * The most recognizable global brands, in Interbrand Best Global Brands 2025
 * order, that have a premium full-color brand SVG. Every entry has both files
 * on disk under apps/web/public.
 */
export type Company = {
  readonly rank: number;
  /** Stock ticker, when the brand is itself a listed company. */
  readonly ticker?: string;
  readonly name: string;
  readonly slug: string;
  readonly svgPath: string;
  readonly gainmapPath: string;
};

export const COMPANIES: readonly Company[] = [
${rows}
];

export function companyBySlug(slug: string): Company | undefined {
  return COMPANIES.find((company) => company.slug === slug);
}

export const LOGO_SRC_WIDTHS = [128, 256, 512, 768, 1024] as const;

export function logoGainmapSrcset(company: Company): string {
  return LOGO_SRC_WIDTHS.map(w => \`/logos/\${company.slug}/logo-gainmap-\${w}.jpg \${w}w\`).join(", ");
}
`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}
